/// GET 接口假数据。
const Map<String, Object> mockGetApiData = {
  '/api/home': {
    'cabinetName': '智能文件保管柜',
    'cabinetCode': 'CAB-A01',
    'region': 'A · B 区',
    'status': '在线运行',
    'headline': '智能柜统计信息',
    'stats': {
      'documentCount': '12 份',
      'occupiedSlots': '6 / 12',
      'pendingPickup': '3 份',
      'todayStored': '5 份',
      'todayPickedUp': '2 份',
      'occupancyRateText': '50%',
      'occupancyRateValue': 0.5,
    },
    'footer': {
      'statusSummary': 'CAB-A01 · 在线',
      'doorStatus': '柜门已锁定',
      'slotSummary': '格位 A·B 区 · 共 12 个',
    },
  },
  '/api/pickup': {
    'personName': '张晓明',
    'personTitle': '法务合规部 · 高级专员',
    'employeeCode': 'EMP-2026-0612',
    'phone': '138 **** 8621',
    'idCard': '310***********0426',
    'organization': '上海总部 / 法务合规中心',
    'permissionLevel': 'L3 · 机密文件取件权限',
    'faceResult': '已通过  13:45:18',
    'fingerprintResult': '已通过  13:45:26',
    'nfcResult': '已通过  13:45:33',
    'pickupCodeResult': '已通过  13:45:39',
    'doorNo': 'A-08',
    'doorLocation': 'A区第2列第4格 · 标准文件柜 · 已授权',
    'fileName': '张晓明 - 法务合规部取件资料',
    'pickupSuccessSummary': '已取出 1 份文件 · 张晓明 · 法务合规部',
  },
  '/api/dropoff': {
    'personName': '张晓明',
    'employeeCode': 'EMP-2026-0612',
    'department': '法务合规部',
    'permissionLevel': 'L3 · 文件存放权限',
    'fileCode': 'FILE-2026-001',
    'fileName': '合格证原件',
    'frcResult': '已匹配',
    'doorNo': 'A-08',
    'doorLocation': 'A区第2列第4格 · 标准文件柜 · 待开门',
    'openDoorTitle': '柜门 A-08 已打开',
    'successSummary': '已存入 1 份文件 · 柜门 A-08 · 已写入审计日志',
  },
  '/api/flight-inspection': {
    'inspectorName': '李晨',
    'employeeCode': 'INS-2026-014',
    'permissionLevel': 'L3',
    'batchNo': 'FI-20260616-01',
    'tasks': [
      {
        'doorNo': 'A-03',
        'fileCode': 'FILE-2026-FI-003',
        'secretLevel': '机密',
        'department': '法务合规部',
      },
      {
        'doorNo': 'A-08',
        'fileCode': 'FILE-2026-FI-008',
        'secretLevel': '秘密',
        'department': '财务管理部',
      },
      {
        'doorNo': 'B-02',
        'fileCode': 'FILE-2026-FI-102',
        'secretLevel': '内部',
        'department': '行政档案室',
      },
    ],
  },
  '/api/admin/device-status': {
    'cabinetCode': 'CAB-A01',
    'region': 'A · B 区',
    'wifiName': 'SmartCabinet-5G',
    'rj45Status': '未连接',
    'nfcStatus': '正常 · 读卡器在线',
    'fingerprintStatus': '正常 · 指纹模块在线',
    'cabinetBoardStatus': '正常 · 12 路柜控板已连接',
    'scannerStatus': '正常 · 扫码器待命',
  },
};

/// POST 接口假数据。
const Map<String, Object> mockPostApiData = {
  '/api/admin/login': {
    'username': '666666',
    'password': '666666',
    'authorized': true,
    'adminName': '系统管理员',
    'permissionLevel': 'L5 · 设备管理权限',
    'message': '管理员权限校验通过',
  },
};
