import 'package:smart_cabinet/src/app/localization/app_localizations.dart';

const adminLocalizations = {
  'adminLoginTitle': {
    AppLanguage.simplifiedChinese: '管理员后台',
    AppLanguage.traditionalChinese: '管理員後台',
    AppLanguage.english: 'Admin Console',
    AppLanguage.japanese: '管理者コンソール',
  },
  'adminUsernameLabel': {
    AppLanguage.simplifiedChinese: '用户名',
    AppLanguage.traditionalChinese: '使用者名稱',
    AppLanguage.english: 'Username',
    AppLanguage.japanese: 'ユーザー名',
  },
  'adminPasswordLabel': {
    AppLanguage.simplifiedChinese: '密码',
    AppLanguage.traditionalChinese: '密碼',
    AppLanguage.english: 'Password',
    AppLanguage.japanese: 'パスワード',
  },
  'adminRememberPassword': {
    AppLanguage.simplifiedChinese: '记住密码',
    AppLanguage.traditionalChinese: '記住密碼',
    AppLanguage.english: 'Remember Password',
    AppLanguage.japanese: 'パスワードを記憶',
  },
  'adminLoginButton': {
    AppLanguage.simplifiedChinese: '登录',
    AppLanguage.traditionalChinese: '登入',
    AppLanguage.english: 'Log In',
    AppLanguage.japanese: 'ログイン',
  },
  'adminLoginDeniedMessage': {
    AppLanguage.simplifiedChinese: '账号或密码错误，或没有管理员权限',
    AppLanguage.traditionalChinese: '帳號或密碼錯誤，或沒有管理員權限',
    AppLanguage.english:
        'The account or password is incorrect, or admin permission is missing',
    AppLanguage.japanese: 'アカウントまたはパスワードが正しくないか、管理者権限がありません',
  },
  'adminLoginFailureMessage': {
    AppLanguage.simplifiedChinese: '管理员权限校验失败，请稍后重试',
    AppLanguage.traditionalChinese: '管理員權限校驗失敗，請稍後重試',
    AppLanguage.english:
        'Admin permission check failed. Please try again later',
    AppLanguage.japanese: '管理者権限の確認に失敗しました。後でもう一度お試しください',
  },
  'adminInputUsername': {
    AppLanguage.simplifiedChinese: '输入用户名',
    AppLanguage.traditionalChinese: '輸入使用者名稱',
    AppLanguage.english: 'Enter username',
    AppLanguage.japanese: 'ユーザー名を入力',
  },
  'adminInputPassword': {
    AppLanguage.simplifiedChinese: '输入密码',
    AppLanguage.traditionalChinese: '輸入密碼',
    AppLanguage.english: 'Enter password',
    AppLanguage.japanese: 'パスワードを入力',
  },
  'adminVerificationTitle': {
    AppLanguage.simplifiedChinese: '管理员身份校验',
    AppLanguage.traditionalChinese: '管理員身份校驗',
    AppLanguage.english: 'Admin Identity Verification',
    AppLanguage.japanese: '管理者本人確認',
  },
  'adminVerificationBadge': {
    AppLanguage.simplifiedChinese: '身份校验中 · 管理员',
    AppLanguage.traditionalChinese: '身份校驗中 · 管理員',
    AppLanguage.english: 'Verifying · Admin',
    AppLanguage.japanese: '確認中 · 管理者',
  },
  'adminVerificationHeading': {
    AppLanguage.simplifiedChinese: '请完成管理员安全身份认证',
    AppLanguage.traditionalChinese: '請完成管理員安全身份認證',
    AppLanguage.english: 'Complete admin security verification',
    AppLanguage.japanese: '管理者セキュリティ確認を完了してください',
  },
  'adminVerificationDescription': {
    AppLanguage.simplifiedChinese: '登录权限已通过，请继续完成人脸、指纹与 NFC 三项校验',
    AppLanguage.traditionalChinese: '登入權限已通過，請繼續完成人臉、指紋與 NFC 三項校驗',
    AppLanguage.english:
        'Login permission passed. Continue face, fingerprint, and NFC checks',
    AppLanguage.japanese: 'ログイン権限確認済み。顔、指紋、NFC確認を続行してください',
  },
  'adminVerificationProgress': {
    AppLanguage.simplifiedChinese: '已完成 {count} / 3 项认证',
    AppLanguage.traditionalChinese: '已完成 {count} / 3 項認證',
    AppLanguage.english: '{count} / 3 checks completed',
    AppLanguage.japanese: '{count} / 3 件完了',
  },
  'adminConsoleTitle': {
    AppLanguage.simplifiedChinese: '管理员控制台',
    AppLanguage.traditionalChinese: '管理員控制台',
    AppLanguage.english: 'Admin Console',
    AppLanguage.japanese: '管理者コンソール',
  },
  'adminConsoleBadge': {
    AppLanguage.simplifiedChinese: '设备管理 · 管理员',
    AppLanguage.traditionalChinese: '設備管理 · 管理員',
    AppLanguage.english: 'Device Management · Admin',
    AppLanguage.japanese: 'デバイス管理 · 管理者',
  },
  'adminDevicePanelTitle': {
    AppLanguage.simplifiedChinese: '当前柜体所有信息',
    AppLanguage.traditionalChinese: '目前櫃體所有資訊',
    AppLanguage.english: 'Current Cabinet Information',
    AppLanguage.japanese: '現在のキャビネット情報',
  },
  'adminDevicePanelSubtitle': {
    AppLanguage.simplifiedChinese: '柜体、网络、摄像头、NFC 与外设状态',
    AppLanguage.traditionalChinese: '櫃體、網路、攝影機、NFC 與外設狀態',
    AppLanguage.english: 'Cabinet, network, camera, NFC, and peripheral status',
    AppLanguage.japanese: 'キャビネット、ネットワーク、カメラ、NFC、周辺機器の状態',
  },
  'adminDeviceCabinetCode': {
    AppLanguage.simplifiedChinese: '柜体编号',
    AppLanguage.traditionalChinese: '櫃體編號',
    AppLanguage.english: 'Cabinet Code',
    AppLanguage.japanese: 'キャビネット番号',
  },
  'adminDeviceRegion': {
    AppLanguage.simplifiedChinese: '所在区域',
    AppLanguage.traditionalChinese: '所在區域',
    AppLanguage.english: 'Area',
    AppLanguage.japanese: 'エリア',
  },
  'adminDeviceRunningStatus': {
    AppLanguage.simplifiedChinese: '运行状态',
    AppLanguage.traditionalChinese: '運行狀態',
    AppLanguage.english: 'Running Status',
    AppLanguage.japanese: '稼働状態',
  },
  'adminDeviceWifi': {
    AppLanguage.simplifiedChinese: '连接 WiFi',
    AppLanguage.traditionalChinese: '連接 WiFi',
    AppLanguage.english: 'Connected WiFi',
    AppLanguage.japanese: '接続中の WiFi',
  },
  'adminDeviceRj45': {
    AppLanguage.simplifiedChinese: 'RJ45连接',
    AppLanguage.traditionalChinese: 'RJ45連接',
    AppLanguage.english: 'RJ45 Connection',
    AppLanguage.japanese: 'RJ45接続',
  },
  'adminDeviceCamera': {
    AppLanguage.simplifiedChinese: '摄像头',
    AppLanguage.traditionalChinese: '攝影機',
    AppLanguage.english: 'Camera',
    AppLanguage.japanese: 'カメラ',
  },
  'adminCameraFaceRecognition': {
    AppLanguage.simplifiedChinese: '人脸识别摄像头',
    AppLanguage.traditionalChinese: '人臉識別攝影機',
    AppLanguage.english: 'Face Recognition Camera',
    AppLanguage.japanese: '顔認証カメラ',
  },
  'adminCameraOutsideEnvironment': {
    AppLanguage.simplifiedChinese: '柜外环境摄像头',
    AppLanguage.traditionalChinese: '櫃外環境攝影機',
    AppLanguage.english: 'Outside Environment Camera',
    AppLanguage.japanese: '柜外環境カメラ',
  },
  'adminCameraOperationArea': {
    AppLanguage.simplifiedChinese: '操作区摄像头',
    AppLanguage.traditionalChinese: '操作區攝影機',
    AppLanguage.english: 'Operation Area Camera',
    AppLanguage.japanese: '操作エリアカメラ',
  },
  'adminCameraCertificateCapture': {
    AppLanguage.simplifiedChinese: '合格证采集摄像头',
    AppLanguage.traditionalChinese: '合格證採集攝影機',
    AppLanguage.english: 'Certificate Capture Camera',
    AppLanguage.japanese: '合格証撮影カメラ',
  },
  'adminDeviceNfc': {
    AppLanguage.simplifiedChinese: 'NFC',
    AppLanguage.traditionalChinese: 'NFC',
    AppLanguage.english: 'NFC',
    AppLanguage.japanese: 'NFC',
  },
  'adminDeviceFingerprint': {
    AppLanguage.simplifiedChinese: '指纹模块',
    AppLanguage.traditionalChinese: '指紋模組',
    AppLanguage.english: 'Fingerprint Module',
    AppLanguage.japanese: '指紋モジュール',
  },
  'adminDeviceCabinetBoard': {
    AppLanguage.simplifiedChinese: '柜控板',
    AppLanguage.traditionalChinese: '櫃控板',
    AppLanguage.english: 'Cabinet Control Board',
    AppLanguage.japanese: 'キャビネット制御ボード',
  },
  'adminDeviceScanner': {
    AppLanguage.simplifiedChinese: '扫码器',
    AppLanguage.traditionalChinese: '掃碼器',
    AppLanguage.english: 'Scanner',
    AppLanguage.japanese: 'スキャナー',
  },
  'adminFunctionPanelTitle': {
    AppLanguage.simplifiedChinese: '功能列表',
    AppLanguage.traditionalChinese: '功能列表',
    AppLanguage.english: 'Function List',
    AppLanguage.japanese: '機能リスト',
  },
  'adminFunctionPanelSubtitle': {
    AppLanguage.simplifiedChinese: '设备检测与维护入口',
    AppLanguage.traditionalChinese: '設備檢測與維護入口',
    AppLanguage.english: 'Device diagnostics and maintenance actions',
    AppLanguage.japanese: 'デバイス診断とメンテナンス',
  },
  'adminFunctionInitializeData': {
    AppLanguage.simplifiedChinese: '初始化数据',
    AppLanguage.traditionalChinese: '初始化資料',
    AppLanguage.english: 'Initialize Data',
    AppLanguage.japanese: 'データ初期化',
  },
  'adminFunctionInitializeDataDescription': {
    AppLanguage.simplifiedChinese: '清理本地演示数据并重新拉取柜体配置',
    AppLanguage.traditionalChinese: '清理本機演示資料並重新拉取櫃體配置',
    AppLanguage.english:
        'Clear local demo data and reload cabinet configuration',
    AppLanguage.japanese: 'ローカルデモデータを削除し、キャビネット設定を再取得します',
  },
  'adminFunctionResetDevice': {
    AppLanguage.simplifiedChinese: '重置设备',
    AppLanguage.traditionalChinese: '重置設備',
    AppLanguage.english: 'Reset Device',
    AppLanguage.japanese: 'デバイスをリセット',
  },
  'adminFunctionResetDeviceDescription': {
    AppLanguage.simplifiedChinese: '重启外设连接、柜控板与终端运行状态',
    AppLanguage.traditionalChinese: '重啟外設連接、櫃控板與終端運行狀態',
    AppLanguage.english:
        'Restart peripherals, cabinet board, and terminal runtime state',
    AppLanguage.japanese: '周辺機器、制御ボード、端末稼働状態を再起動します',
  },
  'adminFunctionAutoDetect': {
    AppLanguage.simplifiedChinese: '自动检测',
    AppLanguage.traditionalChinese: '自動檢測',
    AppLanguage.english: 'Auto Detect',
    AppLanguage.japanese: '自動検出',
  },
  'adminFunctionAutoDetectDescription': {
    AppLanguage.simplifiedChinese: '自动检查网络、摄像头、NFC、柜控板与扫码器',
    AppLanguage.traditionalChinese: '自動檢查網路、攝影機、NFC、櫃控板與掃碼器',
    AppLanguage.english:
        'Check network, camera, NFC, cabinet board, and scanner automatically',
    AppLanguage.japanese: 'ネットワーク、カメラ、NFC、制御ボード、スキャナーを自動確認します',
  },
  'adminAutoDetectTitle': {
    AppLanguage.simplifiedChinese: '自动检测',
    AppLanguage.traditionalChinese: '自動檢測',
    AppLanguage.english: 'Automatic Detection',
    AppLanguage.japanese: '自動検出',
  },
  'adminAutoDetectSubtitle': {
    AppLanguage.simplifiedChinese: '按状态筛选并选择左侧项目查看设备详情',
    AppLanguage.traditionalChinese: '按狀態篩選並選擇左側項目查看設備詳情',
    AppLanguage.english: 'Filter by status and select an item for details',
    AppLanguage.japanese: '状態で絞り込み、左側の項目を選択して詳細を確認します',
  },
  'adminAutoDetectItemsTitle': {
    AppLanguage.simplifiedChinese: '检测项目',
    AppLanguage.traditionalChinese: '檢測項目',
    AppLanguage.english: 'Detection Items',
    AppLanguage.japanese: '検出項目',
  },
  'adminAutoDetectItemDescription': {
    AppLanguage.simplifiedChinese: '检查 {name} 的连接状态与运行结果',
    AppLanguage.traditionalChinese: '檢查 {name} 的連接狀態與運行結果',
    AppLanguage.english: 'Check the connection and operating status of {name}',
    AppLanguage.japanese: '{name} の接続状態と動作結果を確認します',
  },
  'adminAutoDetectEmpty': {
    AppLanguage.simplifiedChinese: '暂无检测项',
    AppLanguage.traditionalChinese: '暫無檢測項',
    AppLanguage.english: 'No detection items',
    AppLanguage.japanese: '検出項目がありません',
  },
  'adminAutoDetectFilteredEmpty': {
    AppLanguage.simplifiedChinese: '当前筛选条件下暂无检测项',
    AppLanguage.traditionalChinese: '目前篩選條件下暫無檢測項',
    AppLanguage.english: 'No items match the current filter',
    AppLanguage.japanese: '現在の絞り込み条件に一致する項目はありません',
  },
  'adminAutoDetectCurrentResult': {
    AppLanguage.simplifiedChinese: '当前检测结果',
    AppLanguage.traditionalChinese: '目前檢測結果',
    AppLanguage.english: 'Current Result',
    AppLanguage.japanese: '現在の検出結果',
  },
  'adminAutoDetectAllCount': {
    AppLanguage.simplifiedChinese: '全部',
    AppLanguage.traditionalChinese: '全部',
    AppLanguage.english: 'All',
    AppLanguage.japanese: 'すべて',
  },
  'adminAutoDetectHealthyCount': {
    AppLanguage.simplifiedChinese: '正常',
    AppLanguage.traditionalChinese: '正常',
    AppLanguage.english: 'Healthy',
    AppLanguage.japanese: '正常',
  },
  'adminAutoDetectAbnormalCount': {
    AppLanguage.simplifiedChinese: '异常',
    AppLanguage.traditionalChinese: '異常',
    AppLanguage.english: 'Abnormal',
    AppLanguage.japanese: '異常',
  },
  'adminAutoDetectPendingCount': {
    AppLanguage.simplifiedChinese: '待接入',
    AppLanguage.traditionalChinese: '待接入',
    AppLanguage.english: 'Pending',
    AppLanguage.japanese: '未接続',
  },
  'adminAutoDetectStatusChecking': {
    AppLanguage.simplifiedChinese: '检测中',
    AppLanguage.traditionalChinese: '檢測中',
    AppLanguage.english: 'Checking',
    AppLanguage.japanese: '検出中',
  },
  'adminAutoDetectStatusHealthy': {
    AppLanguage.simplifiedChinese: '正常',
    AppLanguage.traditionalChinese: '正常',
    AppLanguage.english: 'Healthy',
    AppLanguage.japanese: '正常',
  },
  'adminAutoDetectStatusAbnormal': {
    AppLanguage.simplifiedChinese: '异常',
    AppLanguage.traditionalChinese: '異常',
    AppLanguage.english: 'Abnormal',
    AppLanguage.japanese: '異常',
  },
  'adminAutoDetectStatusPending': {
    AppLanguage.simplifiedChinese: '待接入',
    AppLanguage.traditionalChinese: '待接入',
    AppLanguage.english: 'Pending',
    AppLanguage.japanese: '未接続',
  },
  'adminAutoDetectCheckingResult': {
    AppLanguage.simplifiedChinese: '正在读取设备状态...',
    AppLanguage.traditionalChinese: '正在讀取設備狀態...',
    AppLanguage.english: 'Reading device status...',
    AppLanguage.japanese: 'デバイス状態を読み取り中...',
  },
  'adminAutoDetectConnected': {
    AppLanguage.simplifiedChinese: '连接成功',
    AppLanguage.traditionalChinese: '連接成功',
    AppLanguage.english: 'Connected',
    AppLanguage.japanese: '接続済み',
  },
  'adminAutoDetectDisconnected': {
    AppLanguage.simplifiedChinese: '连接失败',
    AppLanguage.traditionalChinese: '連接失敗',
    AppLanguage.english: 'Connection failed',
    AppLanguage.japanese: '接続失敗',
  },
  'adminAutoDetectSelectedActionHint': {
    AppLanguage.simplifiedChinese: '恢复操作仅作用于当前选中设备',
    AppLanguage.traditionalChinese: '恢復操作僅作用於目前選中設備',
    AppLanguage.english: 'Recovery affects only the selected device',
    AppLanguage.japanese: '復旧操作は選択中のデバイスだけに適用されます',
  },
  'adminAutoDetectInitialLoadFailed': {
    AppLanguage.simplifiedChinese: '自动检测失败：{error}',
    AppLanguage.traditionalChinese: '自動檢測失敗：{error}',
    AppLanguage.english: 'Automatic detection failed: {error}',
    AppLanguage.japanese: '自動検出に失敗しました：{error}',
  },
  'adminAutoDetectReconnectDevice': {
    AppLanguage.simplifiedChinese: '重连该设备',
    AppLanguage.traditionalChinese: '重連該設備',
    AppLanguage.english: 'Reconnect Device',
    AppLanguage.japanese: 'このデバイスを再接続',
  },
  'adminAutoDetectReconnectHint': {
    AppLanguage.simplifiedChinese: '仅重连当前左侧选中的设备',
    AppLanguage.traditionalChinese: '僅重連目前左側選中的設備',
    AppLanguage.english: 'Reconnect only the device selected on the left',
    AppLanguage.japanese: '左側で選択中のデバイスだけを再接続します',
  },
  'adminAutoDetectReconnecting': {
    AppLanguage.simplifiedChinese: '重连中...',
    AppLanguage.traditionalChinese: '重連中...',
    AppLanguage.english: 'Reconnecting...',
    AppLanguage.japanese: '再接続中...',
  },
  'adminAutoDetectReconnectPending': {
    AppLanguage.simplifiedChinese: '{name} 的重连接口待接入',
    AppLanguage.traditionalChinese: '{name} 的重連接口待接入',
    AppLanguage.english: 'Reconnect support for {name} is not connected yet',
    AppLanguage.japanese: '{name} の再接続機能は未接続です',
  },
  'adminAutoDetectReconnectSucceeded': {
    AppLanguage.simplifiedChinese: '{name} 已完成重连',
    AppLanguage.traditionalChinese: '{name} 已完成重連',
    AppLanguage.english: '{name} reconnected successfully',
    AppLanguage.japanese: '{name} の再接続が完了しました',
  },
  'adminAutoDetectReconnectFailed': {
    AppLanguage.simplifiedChinese: '{name} 重连失败：{error}',
    AppLanguage.traditionalChinese: '{name} 重連失敗：{error}',
    AppLanguage.english: 'Failed to reconnect {name}: {error}',
    AppLanguage.japanese: '{name} の再接続に失敗しました：{error}',
  },
  'adminAutoDetectClose': {
    AppLanguage.simplifiedChinese: '关闭',
    AppLanguage.traditionalChinese: '關閉',
    AppLanguage.english: 'Close',
    AppLanguage.japanese: '閉じる',
  },
  'adminFunctionIndexTitle': {
    AppLanguage.simplifiedChinese: '{index}、{title}',
    AppLanguage.traditionalChinese: '{index}、{title}',
    AppLanguage.english: '{index}. {title}',
    AppLanguage.japanese: '{index}. {title}',
  },
  'adminFunctionPendingMessage': {
    AppLanguage.simplifiedChinese: '{name} 功能待接入真实设备接口',
    AppLanguage.traditionalChinese: '{name} 功能待接入真實設備接口',
    AppLanguage.english: '{name} will be connected to real device APIs later',
    AppLanguage.japanese: '{name} は後で実機 API に接続されます',
  },
  'adminFunctionTerminalUpgrade': {
    AppLanguage.simplifiedChinese: '终端升级',
    AppLanguage.traditionalChinese: '終端升級',
    AppLanguage.english: 'Terminal Upgrade',
    AppLanguage.japanese: '端末アップグレード',
  },
  'adminFunctionTerminalUpgradeDescription': {
    AppLanguage.simplifiedChinese: '连接 ZRD 升级服务，检查并安全安装 URL 升级包',
    AppLanguage.traditionalChinese: '連線 ZRD 升級服務，檢查並安全安裝 URL 升級套件',
    AppLanguage.english:
        'Connect to ZRD upgrade services and safely install URL packages',
    AppLanguage.japanese: 'ZRD 更新サービスに接続し、URL パッケージを安全にインストールします',
  },
  'adminFunctionCommunicationLog': {
    AppLanguage.simplifiedChinese: '通讯日志',
    AppLanguage.traditionalChinese: '通訊日誌',
    AppLanguage.english: 'Communication Logs',
    AppLanguage.japanese: '通信ログ',
  },
  'adminFunctionCommunicationLogDescription': {
    AppLanguage.simplifiedChinese: '查看软件与服务器、硬件之间的实时指令记录',
    AppLanguage.traditionalChinese: '查看軟體與伺服器、硬體之間的即時指令記錄',
    AppLanguage.english:
        'View real-time command records between the app, server, and hardware',
    AppLanguage.japanese: 'アプリとサーバー・ハードウェア間のリアルタイム指令記録を確認します',
  },
  'adminCommunicationLogTitle': {
    AppLanguage.simplifiedChinese: '通讯日志',
    AppLanguage.traditionalChinese: '通訊日誌',
    AppLanguage.english: 'Communication Logs',
    AppLanguage.japanese: '通信ログ',
  },
  'adminCommunicationLogBadge': {
    AppLanguage.simplifiedChinese: '设备通讯 · 管理员',
    AppLanguage.traditionalChinese: '設備通訊 · 管理員',
    AppLanguage.english: 'Device Communication · Admin',
    AppLanguage.japanese: 'デバイス通信 · 管理者',
  },
  'adminCommunicationLogTableTitle': {
    AppLanguage.simplifiedChinese: '通讯记录',
    AppLanguage.traditionalChinese: '通訊記錄',
    AppLanguage.english: 'Communication Records',
    AppLanguage.japanese: '通信記録',
  },
  'adminCommunicationLogRecordCount': {
    AppLanguage.simplifiedChinese: '当前共 {count} 条记录',
    AppLanguage.traditionalChinese: '目前共 {count} 筆記錄',
    AppLanguage.english: '{count} records',
    AppLanguage.japanese: '現在 {count} 件の記録',
  },
  'adminCommunicationLogEmpty': {
    AppLanguage.simplifiedChinese: '暂无通讯日志',
    AppLanguage.traditionalChinese: '暫無通訊日誌',
    AppLanguage.english: 'No communication logs',
    AppLanguage.japanese: '通信ログはありません',
  },
  'adminCommunicationLogTypeColumn': {
    AppLanguage.simplifiedChinese: '类型',
    AppLanguage.traditionalChinese: '類型',
    AppLanguage.english: 'Type',
    AppLanguage.japanese: '種別',
  },
  'adminCommunicationLogDirectionColumn': {
    AppLanguage.simplifiedChinese: '发送类型',
    AppLanguage.traditionalChinese: '傳送類型',
    AppLanguage.english: 'Direction',
    AppLanguage.japanese: '送受信種別',
  },
  'adminCommunicationLogMessageBodyColumn': {
    AppLanguage.simplifiedChinese: '消息体',
    AppLanguage.traditionalChinese: '訊息內容',
    AppLanguage.english: 'Message Body',
    AppLanguage.japanese: 'メッセージ本文',
  },
  'adminCommunicationLogRequestTimeColumn': {
    AppLanguage.simplifiedChinese: '请求时间',
    AppLanguage.traditionalChinese: '請求時間',
    AppLanguage.english: 'Request Time',
    AppLanguage.japanese: 'リクエスト日時',
  },
  'adminCommunicationLogResultColumn': {
    AppLanguage.simplifiedChinese: '请求结果',
    AppLanguage.traditionalChinese: '請求結果',
    AppLanguage.english: 'Request Result',
    AppLanguage.japanese: 'リクエスト結果',
  },
  'adminCommunicationLogEmptyMessageBody': {
    AppLanguage.simplifiedChinese: '（空消息体）',
    AppLanguage.traditionalChinese: '（空訊息內容）',
    AppLanguage.english: '(Empty message body)',
    AppLanguage.japanese: '（空のメッセージ本文）',
  },
  'adminCommunicationLogDetailTitle': {
    AppLanguage.simplifiedChinese: '通讯日志详情',
    AppLanguage.traditionalChinese: '通訊日誌詳情',
    AppLanguage.english: 'Communication Log Details',
    AppLanguage.japanese: '通信ログ詳細',
  },
  'adminCommunicationLogCloseDetail': {
    AppLanguage.simplifiedChinese: '关闭',
    AppLanguage.traditionalChinese: '關閉',
    AppLanguage.english: 'Close',
    AppLanguage.japanese: '閉じる',
  },
  'adminCommunicationLogCompleteInformation': {
    AppLanguage.simplifiedChinese: '完整信息（已脱敏）',
    AppLanguage.traditionalChinese: '完整資訊（已脫敏）',
    AppLanguage.english: 'Complete Information (Redacted)',
    AppLanguage.japanese: '完全な情報（マスキング済み）',
  },
  'adminCommunicationLogServerType': {
    AppLanguage.simplifiedChinese: '服务器',
    AppLanguage.traditionalChinese: '伺服器',
    AppLanguage.english: 'Server',
    AppLanguage.japanese: 'サーバー',
  },
  'adminCommunicationLogHardwareType': {
    AppLanguage.simplifiedChinese: '硬件',
    AppLanguage.traditionalChinese: '硬體',
    AppLanguage.english: 'Hardware',
    AppLanguage.japanese: 'ハードウェア',
  },
  'adminCommunicationLogUpgradeCommandType': {
    AppLanguage.simplifiedChinese: '升级指令',
    AppLanguage.traditionalChinese: '升級指令',
    AppLanguage.english: 'Upgrade Command',
    AppLanguage.japanese: 'アップグレード指令',
  },
  'adminCommunicationLogOutboundDirection': {
    AppLanguage.simplifiedChinese: '上报',
    AppLanguage.traditionalChinese: '上報',
    AppLanguage.english: 'Outbound (Report)',
    AppLanguage.japanese: '送信（上報）',
  },
  'adminCommunicationLogInboundDirection': {
    AppLanguage.simplifiedChinese: '下发',
    AppLanguage.traditionalChinese: '下發',
    AppLanguage.english: 'Inbound (Downlink)',
    AppLanguage.japanese: '受信（下り）',
  },
  'adminLoginSubtitleTitle': {
    AppLanguage.simplifiedChinese: '智能柜管理后台',
    AppLanguage.traditionalChinese: '智慧櫃管理後台',
    AppLanguage.english: 'Smart Cabinet Administration',
    AppLanguage.japanese: 'スマートキャビネット管理',
  },
  'adminLoginSubtitleDescription': {
    AppLanguage.simplifiedChinese: '设备状态、格口权限与业务记录统一管控',
    AppLanguage.traditionalChinese: '統一管理設備狀態、格口權限與業務記錄',
    AppLanguage.english:
        'Manage device status, compartment access, and operation records',
    AppLanguage.japanese: 'デバイス状態、区画権限、業務記録を一元管理',
  },
  'adminKeyboardBack': {
    AppLanguage.simplifiedChinese: '返回',
    AppLanguage.traditionalChinese: '返回',
    AppLanguage.english: 'Back',
    AppLanguage.japanese: '戻る',
  },
  'adminKeyboardHint': {
    AppLanguage.simplifiedChinese: '使用左侧数字键盘录入',
    AppLanguage.traditionalChinese: '使用左側數字鍵盤輸入',
    AppLanguage.english: 'Enter the value with the number pad on the left',
    AppLanguage.japanese: '左側の数字キーパッドで入力してください',
  },
  'adminKeyboardClear': {
    AppLanguage.simplifiedChinese: '清空',
    AppLanguage.traditionalChinese: '清除',
    AppLanguage.english: 'Clear',
    AppLanguage.japanese: 'クリア',
  },
  'adminKeyboardDelete': {
    AppLanguage.simplifiedChinese: '删除',
    AppLanguage.traditionalChinese: '刪除',
    AppLanguage.english: 'Delete',
    AppLanguage.japanese: '削除',
  },
  'adminBackTooltip': {
    AppLanguage.simplifiedChinese: '返回',
    AppLanguage.traditionalChinese: '返回',
    AppLanguage.english: 'Back',
    AppLanguage.japanese: '戻る',
  },
  'adminCloseTooltip': {
    AppLanguage.simplifiedChinese: '关闭',
    AppLanguage.traditionalChinese: '關閉',
    AppLanguage.english: 'Close',
    AppLanguage.japanese: '閉じる',
  },
  'adminLabelSeparator': {
    AppLanguage.simplifiedChinese: '：',
    AppLanguage.traditionalChinese: '：',
    AppLanguage.english: ': ',
    AppLanguage.japanese: '：',
  },
  'adminStatusReading': {
    AppLanguage.simplifiedChinese: '正在读取',
    AppLanguage.traditionalChinese: '正在讀取',
    AppLanguage.english: 'Reading',
    AppLanguage.japanese: '読み取り中',
  },
  'adminStatusDetecting': {
    AppLanguage.simplifiedChinese: '正在检测',
    AppLanguage.traditionalChinese: '檢測中',
    AppLanguage.english: 'Detecting',
    AppLanguage.japanese: '検出中',
  },
  'adminStatusPending': {
    AppLanguage.simplifiedChinese: '待接入',
    AppLanguage.traditionalChinese: '待接入',
    AppLanguage.english: 'Pending',
    AppLanguage.japanese: '未接続',
  },
  'adminStatusConnected': {
    AppLanguage.simplifiedChinese: '已连接',
    AppLanguage.traditionalChinese: '已連線',
    AppLanguage.english: 'Connected',
    AppLanguage.japanese: '接続済み',
  },
  'adminStatusDisconnected': {
    AppLanguage.simplifiedChinese: '未连接',
    AppLanguage.traditionalChinese: '未連線',
    AppLanguage.english: 'Disconnected',
    AppLanguage.japanese: '未接続',
  },
  'adminStatusAvailable': {
    AppLanguage.simplifiedChinese: '可用',
    AppLanguage.traditionalChinese: '可用',
    AppLanguage.english: 'Available',
    AppLanguage.japanese: '利用可能',
  },
  'adminStatusUnavailable': {
    AppLanguage.simplifiedChinese: '不可用',
    AppLanguage.traditionalChinese: '不可用',
    AppLanguage.english: 'Unavailable',
    AppLanguage.japanese: '利用不可',
  },
  'adminStatusUnknownDevice': {
    AppLanguage.simplifiedChinese: '未知设备',
    AppLanguage.traditionalChinese: '未知設備',
    AppLanguage.english: 'Unknown device',
    AppLanguage.japanese: '不明なデバイス',
  },
  'adminStatusNotConfigured': {
    AppLanguage.simplifiedChinese: '未配置',
    AppLanguage.traditionalChinese: '未設定',
    AppLanguage.english: 'Not configured',
    AppLanguage.japanese: '未設定',
  },
  'adminStatusWifiConnected': {
    AppLanguage.simplifiedChinese: '已连接 WiFi',
    AppLanguage.traditionalChinese: '已連線 WiFi',
    AppLanguage.english: 'Wi-Fi connected',
    AppLanguage.japanese: 'Wi-Fi 接続済み',
  },
  'adminDeviceStatusReadFailed': {
    AppLanguage.simplifiedChinese: '硬件状态读取失败',
    AppLanguage.traditionalChinese: '硬體狀態讀取失敗',
    AppLanguage.english: 'Failed to read hardware status',
    AppLanguage.japanese: 'ハードウェア状態を読み取れませんでした',
  },
  'adminConsoleClosed': {
    AppLanguage.simplifiedChinese: '管理员控制台已关闭',
    AppLanguage.traditionalChinese: '管理員控制台已關閉',
    AppLanguage.english: 'The admin console has been closed',
    AppLanguage.japanese: '管理者コンソールは閉じられました',
  },
  'adminCameraLoading': {
    AppLanguage.simplifiedChinese: '正在读取摄像头...',
    AppLanguage.traditionalChinese: '正在讀取攝影機...',
    AppLanguage.english: 'Reading camera status...',
    AppLanguage.japanese: 'カメラ状態を読み取り中...',
  },
  'adminCameraConnectionProbeError': {
    AppLanguage.simplifiedChinese: '连接检测异常',
    AppLanguage.traditionalChinese: '連線檢測異常',
    AppLanguage.english: 'Connection check error',
    AppLanguage.japanese: '接続確認エラー',
  },
  'adminCameraConnectionProbeErrorCode': {
    AppLanguage.simplifiedChinese: '连接检测异常（{code}）',
    AppLanguage.traditionalChinese: '連線檢測異常（{code}）',
    AppLanguage.english: 'Connection check error ({code})',
    AppLanguage.japanese: '接続確認エラー（{code}）',
  },
  'adminCameraDetectionFailed': {
    AppLanguage.simplifiedChinese: '检测失败',
    AppLanguage.traditionalChinese: '檢測失敗',
    AppLanguage.english: 'Detection failed',
    AppLanguage.japanese: '検出失敗',
  },
  'adminCameraConnectionSummary': {
    AppLanguage.simplifiedChinese: '设备连接：{status}',
    AppLanguage.traditionalChinese: '設備連線：{status}',
    AppLanguage.english: 'Device connection: {status}',
    AppLanguage.japanese: 'デバイス接続：{status}',
  },
  'adminCameraStreamSummary': {
    AppLanguage.simplifiedChinese: '视频推流：{status}',
    AppLanguage.traditionalChinese: '視訊串流：{status}',
    AppLanguage.english: 'Video stream: {status}',
    AppLanguage.japanese: '映像ストリーム：{status}',
  },
  'adminCameraStreamNotStarted': {
    AppLanguage.simplifiedChinese: '未启动',
    AppLanguage.traditionalChinese: '未啟動',
    AppLanguage.english: 'Not started',
    AppLanguage.japanese: '未開始',
  },
  'adminCameraStreamReadFailed': {
    AppLanguage.simplifiedChinese: '状态读取失败',
    AppLanguage.traditionalChinese: '狀態讀取失敗',
    AppLanguage.english: 'Failed to read status',
    AppLanguage.japanese: '状態を読み取れませんでした',
  },
  'adminCameraStreaming': {
    AppLanguage.simplifiedChinese: '推流中',
    AppLanguage.traditionalChinese: '串流中',
    AppLanguage.english: 'Streaming',
    AppLanguage.japanese: 'ストリーミング中',
  },
  'adminCameraStreamingProfile': {
    AppLanguage.simplifiedChinese: '{profile} 推流中',
    AppLanguage.traditionalChinese: '{profile} 串流中',
    AppLanguage.english: 'Streaming {profile}',
    AppLanguage.japanese: '{profile} でストリーミング中',
  },
  'adminCameraStreamStarting': {
    AppLanguage.simplifiedChinese: '启动中',
    AppLanguage.traditionalChinese: '啟動中',
    AppLanguage.english: 'Starting',
    AppLanguage.japanese: '開始中',
  },
  'adminCameraStreamReconnecting': {
    AppLanguage.simplifiedChinese: '自动重连中',
    AppLanguage.traditionalChinese: '自動重新連線中',
    AppLanguage.english: 'Reconnecting automatically',
    AppLanguage.japanese: '自動再接続中',
  },
  'adminCameraStreamReconnectingAttempt': {
    AppLanguage.simplifiedChinese: '自动重连中（第 {count} 次）',
    AppLanguage.traditionalChinese: '自動重新連線中（第 {count} 次）',
    AppLanguage.english: 'Reconnecting automatically (attempt {count})',
    AppLanguage.japanese: '自動再接続中（{count} 回目）',
  },
  'adminCameraStreamFailedSeeDetails': {
    AppLanguage.simplifiedChinese: '推流失败（详见推流异常提示）',
    AppLanguage.traditionalChinese: '串流失敗（詳見串流異常提示）',
    AppLanguage.english: 'Streaming failed (see the stream error)',
    AppLanguage.japanese: 'ストリーミング失敗（詳細はエラー表示を参照）',
  },
  'adminCameraStreamStopping': {
    AppLanguage.simplifiedChinese: '停止中',
    AppLanguage.traditionalChinese: '停止中',
    AppLanguage.english: 'Stopping',
    AppLanguage.japanese: '停止中',
  },
  'adminCameraStreamUnknown': {
    AppLanguage.simplifiedChinese: '状态未知',
    AppLanguage.traditionalChinese: '狀態未知',
    AppLanguage.english: 'Unknown status',
    AppLanguage.japanese: '状態不明',
  },
  'adminCameraRetryUnknownStream': {
    AppLanguage.simplifiedChinese: '无法识别要重试的视频流',
    AppLanguage.traditionalChinese: '無法識別要重試的視訊串流',
    AppLanguage.english: 'The video stream to retry could not be identified',
    AppLanguage.japanese: '再試行する映像ストリームを特定できません',
  },
  'adminCameraRetryProbeFailed': {
    AppLanguage.simplifiedChinese: '设备连接检测异常，无法重试视频推流',
    AppLanguage.traditionalChinese: '設備連線檢測異常，無法重試視訊串流',
    AppLanguage.english:
        'The connection check failed, so the video stream cannot be retried',
    AppLanguage.japanese: '接続確認に失敗したため、映像ストリームを再試行できません',
  },
  'adminCameraRetryDisconnected': {
    AppLanguage.simplifiedChinese: '设备未连接，无法重试视频推流',
    AppLanguage.traditionalChinese: '設備未連線，無法重試視訊串流',
    AppLanguage.english:
        'The device is disconnected, so the video stream cannot be retried',
    AppLanguage.japanese: 'デバイスが未接続のため、映像ストリームを再試行できません',
  },
  'adminCameraNoRecoverableProfiles': {
    AppLanguage.simplifiedChinese: '当前没有可恢复的推流清晰度，请由手机端重新发起推流',
    AppLanguage.traditionalChinese: '目前沒有可恢復的串流畫質，請從手機端重新發起串流',
    AppLanguage.english:
        'No stream profile can be recovered. Start streaming again from the mobile app.',
    AppLanguage.japanese: '復旧可能な画質設定がありません。モバイル側からストリーミングを再開してください',
  },
  'adminCameraStreamStartFailed': {
    AppLanguage.simplifiedChinese: '视频推流启动失败',
    AppLanguage.traditionalChinese: '視訊串流啟動失敗',
    AppLanguage.english: 'Failed to start video streaming',
    AppLanguage.japanese: '映像ストリーミングを開始できませんでした',
  },
  'adminCameraStreamRecoveryTimedOut': {
    AppLanguage.simplifiedChinese: '等待视频推流恢复超时',
    AppLanguage.traditionalChinese: '等待視訊串流恢復逾時',
    AppLanguage.english: 'Timed out waiting for video streaming to recover',
    AppLanguage.japanese: '映像ストリーミングの復旧待ちがタイムアウトしました',
  },
  'adminCameraPreviewStarting': {
    AppLanguage.simplifiedChinese: '正在启动预览...',
    AppLanguage.traditionalChinese: '正在啟動預覽...',
    AppLanguage.english: 'Starting preview...',
    AppLanguage.japanese: 'プレビューを開始中...',
  },
  'adminCameraPreviewStarted': {
    AppLanguage.simplifiedChinese: '预览已启动',
    AppLanguage.traditionalChinese: '預覽已啟動',
    AppLanguage.english: 'Preview started',
    AppLanguage.japanese: 'プレビュー開始済み',
  },
  'adminCameraPreviewTitle': {
    AppLanguage.simplifiedChinese: '{name}预览',
    AppLanguage.traditionalChinese: '{name}預覽',
    AppLanguage.english: '{name} Preview',
    AppLanguage.japanese: '{name}プレビュー',
  },
  'adminCameraPreviewErrorPrefix': {
    AppLanguage.simplifiedChinese: '预览异常',
    AppLanguage.traditionalChinese: '預覽異常',
    AppLanguage.english: 'Preview error',
    AppLanguage.japanese: 'プレビューエラー',
  },
  'adminCameraPreviewErrorInUse': {
    AppLanguage.simplifiedChinese: '预览异常：摄像头正被其他页面或应用占用，请先关闭其他预览',
    AppLanguage.traditionalChinese: '預覽異常：攝影機正由其他頁面或應用程式使用，請先關閉其他預覽',
    AppLanguage.english:
        'Preview error: the camera is in use. Close other previews first.',
    AppLanguage.japanese: 'プレビューエラー：カメラは使用中です。先に他のプレビューを閉じてください',
  },
  'adminCameraPreviewErrorLimit': {
    AppLanguage.simplifiedChinese: '预览异常：已达到系统同时打开摄像头上限，请先关闭其他摄像头',
    AppLanguage.traditionalChinese: '預覽異常：已達系統同時開啟攝影機上限，請先關閉其他攝影機',
    AppLanguage.english:
        'Preview error: the open-camera limit was reached. Close another camera first.',
    AppLanguage.japanese: 'プレビューエラー：同時に開けるカメラ数の上限です。先に他のカメラを閉じてください',
  },
  'adminCameraPreviewErrorUnavailable': {
    AppLanguage.simplifiedChinese: '预览异常：摄像头暂时不可用',
    AppLanguage.traditionalChinese: '預覽異常：攝影機暫時不可用',
    AppLanguage.english: 'Preview error: the camera is temporarily unavailable',
    AppLanguage.japanese: 'プレビューエラー：カメラは一時的に利用できません',
  },
  'adminCameraPreviewErrorDetail': {
    AppLanguage.simplifiedChinese: '预览异常：{detail}',
    AppLanguage.traditionalChinese: '預覽異常：{detail}',
    AppLanguage.english: 'Preview error: {detail}',
    AppLanguage.japanese: 'プレビューエラー：{detail}',
  },
  'adminCameraCapabilityTitle': {
    AppLanguage.simplifiedChinese: '摄像头能力（仅供诊断）',
    AppLanguage.traditionalChinese: '攝影機能力（僅供診斷）',
    AppLanguage.english: 'Camera Capabilities (Diagnostics Only)',
    AppLanguage.japanese: 'カメラ機能（診断専用）',
  },
  'adminCameraPreviewStatusLabel': {
    AppLanguage.simplifiedChinese: '预览状态',
    AppLanguage.traditionalChinese: '預覽狀態',
    AppLanguage.english: 'Preview Status',
    AppLanguage.japanese: 'プレビュー状態',
  },
  'adminCameraPreviewIdLabel': {
    AppLanguage.simplifiedChinese: '预览摄像头 ID',
    AppLanguage.traditionalChinese: '預覽攝影機 ID',
    AppLanguage.english: 'Preview Camera ID',
    AppLanguage.japanese: 'プレビューカメラ ID',
  },
  'adminCameraCapabilityLabel': {
    AppLanguage.simplifiedChinese: '设备能力',
    AppLanguage.traditionalChinese: '設備能力',
    AppLanguage.english: 'Device Capabilities',
    AppLanguage.japanese: 'デバイス機能',
  },
  'adminCameraCapabilityReading': {
    AppLanguage.simplifiedChinese: '正在读取...',
    AppLanguage.traditionalChinese: '正在讀取...',
    AppLanguage.english: 'Reading...',
    AppLanguage.japanese: '読み取り中...',
  },
  'adminCameraCapabilityReadFailed': {
    AppLanguage.simplifiedChinese: '读取失败',
    AppLanguage.traditionalChinese: '讀取失敗',
    AppLanguage.english: 'Read failed',
    AppLanguage.japanese: '読み取り失敗',
  },
  'adminCameraBoundIdLabel': {
    AppLanguage.simplifiedChinese: '绑定 Camera2 ID',
    AppLanguage.traditionalChinese: '綁定 Camera2 ID',
    AppLanguage.english: 'Bound Camera2 ID',
    AppLanguage.japanese: '割り当て済み Camera2 ID',
  },
  'adminCameraCurrentIdsLabel': {
    AppLanguage.simplifiedChinese: '系统当前 ID',
    AppLanguage.traditionalChinese: '系統目前 ID',
    AppLanguage.english: 'Current System IDs',
    AppLanguage.japanese: '現在のシステム ID',
  },
  'adminCameraNotEnumerated': {
    AppLanguage.simplifiedChinese: '未枚举到摄像头',
    AppLanguage.traditionalChinese: '未列舉到攝影機',
    AppLanguage.english: 'No cameras enumerated',
    AppLanguage.japanese: 'カメラを列挙できませんでした',
  },
  'adminCameraSupportedYuvLabel': {
    AppLanguage.simplifiedChinese: '支持的 YUV 分辨率',
    AppLanguage.traditionalChinese: '支援的 YUV 解析度',
    AppLanguage.english: 'Supported YUV Resolutions',
    AppLanguage.japanese: '対応 YUV 解像度',
  },
  'adminCameraStreamProfileLabel': {
    AppLanguage.simplifiedChinese: '推流配置',
    AppLanguage.traditionalChinese: '串流設定',
    AppLanguage.english: 'Stream Profiles',
    AppLanguage.japanese: 'ストリーム設定',
  },
  'adminCameraCapabilityReadWarning': {
    AppLanguage.simplifiedChinese: '能力信息读取失败不会影响上方实时预览。',
    AppLanguage.traditionalChinese: '能力資訊讀取失敗不會影響上方即時預覽。',
    AppLanguage.english:
        'Failure to read capability data does not affect the live preview above.',
    AppLanguage.japanese: '機能情報の読み取り失敗は、上のライブプレビューには影響しません。',
  },
  'adminCameraBoundUnavailable': {
    AppLanguage.simplifiedChinese: '绑定的摄像头当前不可用，请检查接线、设备 ID 或是否被系统移除。',
    AppLanguage.traditionalChinese: '綁定的攝影機目前不可用，請檢查接線、設備 ID 或是否已被系統移除。',
    AppLanguage.english:
        'The bound camera is unavailable. Check its cable, device ID, and system presence.',
    AppLanguage.japanese: '割り当てたカメラを利用できません。配線、デバイス ID、システムからの削除有無を確認してください。',
  },
  'adminCameraUnsupportedProfiles': {
    AppLanguage.simplifiedChinese:
        '不支持推流配置：{profiles}。收到推流请求时会在打开摄像头前停止，并返回明确错误。',
    AppLanguage.traditionalChinese:
        '不支援串流設定：{profiles}。收到串流請求時會在開啟攝影機前停止，並回傳明確錯誤。',
    AppLanguage.english:
        'Unsupported stream profiles: {profiles}. Requests stop before opening the camera and return a clear error.',
    AppLanguage.japanese: '非対応のストリーム設定：{profiles}。要求はカメラを開く前に停止し、明確なエラーを返します。',
  },
  'adminCameraNoYuvSizes': {
    AppLanguage.simplifiedChinese: '未获取到',
    AppLanguage.traditionalChinese: '未取得',
    AppLanguage.english: 'Not available',
    AppLanguage.japanese: '取得できませんでした',
  },
  'adminCameraAdditionalSizes': {
    AppLanguage.simplifiedChinese: ' 等 {count} 种',
    AppLanguage.traditionalChinese: ' 等 {count} 種',
    AppLanguage.english: ' ({count} total)',
    AppLanguage.japanese: '（全 {count} 種）',
  },
  'adminCameraNativeStreamUnused': {
    AppLanguage.simplifiedChinese: '该角色不使用原生推流',
    AppLanguage.traditionalChinese: '此角色不使用原生串流',
    AppLanguage.english: 'This role does not use native streaming',
    AppLanguage.japanese: 'この役割ではネイティブストリーミングを使用しません',
  },
  'adminCameraProfileSupported': {
    AppLanguage.simplifiedChinese: '支持',
    AppLanguage.traditionalChinese: '支援',
    AppLanguage.english: 'Supported',
    AppLanguage.japanese: '対応',
  },
  'adminCameraProfileUnsupported': {
    AppLanguage.simplifiedChinese: '不支持',
    AppLanguage.traditionalChinese: '不支援',
    AppLanguage.english: 'Unsupported',
    AppLanguage.japanese: '非対応',
  },
  'adminCameraProfilePending': {
    AppLanguage.simplifiedChinese: '待确认',
    AppLanguage.traditionalChinese: '待確認',
    AppLanguage.english: 'Pending confirmation',
    AppLanguage.japanese: '確認待ち',
  },
  'adminCameraDiagnosticCode': {
    AppLanguage.simplifiedChinese: '摄像头诊断代码：{code}',
    AppLanguage.traditionalChinese: '攝影機診斷代碼：{code}',
    AppLanguage.english: 'Camera diagnostic code: {code}',
    AppLanguage.japanese: 'カメラ診断コード：{code}',
  },
  'adminAutoDetectPendingDriver': {
    AppLanguage.simplifiedChinese: '待接入驱动与检测接口',
    AppLanguage.traditionalChinese: '待接入驅動程式與檢測介面',
    AppLanguage.english: 'Driver and detection API pending',
    AppLanguage.japanese: 'ドライバーと検出 API は未接続です',
  },
  'adminAutoDetectCabinetBoardRecoveryUnsupported': {
    AppLanguage.simplifiedChinese: '系统尚未接入柜控板驱动与重连接口',
    AppLanguage.traditionalChinese: '系統尚未接入櫃控板驅動程式與重新連線介面',
    AppLanguage.english:
        'Cabinet-board driver and reconnect support are not connected yet',
    AppLanguage.japanese: 'キャビネット制御基板のドライバーと再接続機能は未接続です',
  },
  'adminAutoDetectScannerRecoveryUnsupported': {
    AppLanguage.simplifiedChinese: '系统尚未接入扫码器驱动与重连接口',
    AppLanguage.traditionalChinese: '系統尚未接入掃碼器驅動程式與重新連線介面',
    AppLanguage.english:
        'Scanner driver and reconnect support are not connected yet',
    AppLanguage.japanese: 'スキャナーのドライバーと再接続機能は未接続です',
  },
  'adminAutoDetectRecoveryUnsupported': {
    AppLanguage.simplifiedChinese: '当前设备不支持自动恢复',
    AppLanguage.traditionalChinese: '目前設備不支援自動恢復',
    AppLanguage.english: 'This device does not support automatic recovery',
    AppLanguage.japanese: 'このデバイスは自動復旧に対応していません',
  },
  'adminAutoDetectRecoveryPending': {
    AppLanguage.simplifiedChinese: '{name} 的恢复处理尚未接入',
    AppLanguage.traditionalChinese: '{name} 的恢復處理尚未接入',
    AppLanguage.english: 'Recovery support for {name} is not connected yet',
    AppLanguage.japanese: '{name} の復旧処理は未接続です',
  },
  'adminAutoDetectStreamRecovered': {
    AppLanguage.simplifiedChinese: '{name} 推流已恢复',
    AppLanguage.traditionalChinese: '{name} 串流已恢復',
    AppLanguage.english: '{name} streaming recovered',
    AppLanguage.japanese: '{name} のストリーミングが復旧しました',
  },
  'adminAutoDetectRecheckSucceeded': {
    AppLanguage.simplifiedChinese: '{name} 重新检测通过',
    AppLanguage.traditionalChinese: '{name} 重新檢測通過',
    AppLanguage.english: '{name} passed the new check',
    AppLanguage.japanese: '{name} の再検出に成功しました',
  },
  'adminAutoDetectStreamVerificationFailed': {
    AppLanguage.simplifiedChinese: '复检后视频流仍未进入推流中状态',
    AppLanguage.traditionalChinese: '複檢後視訊串流仍未進入串流狀態',
    AppLanguage.english:
        'The video stream is still not streaming after recheck',
    AppLanguage.japanese: '再検出後も映像ストリームが開始されていません',
  },
  'adminAutoDetectDeviceVerificationFailed': {
    AppLanguage.simplifiedChinese: '复检后设备状态仍未恢复正常',
    AppLanguage.traditionalChinese: '複檢後設備狀態仍未恢復正常',
    AppLanguage.english: 'The device is still unhealthy after recheck',
    AppLanguage.japanese: '再検出後もデバイス状態が正常に戻っていません',
  },
  'adminAutoDetectRecoveryFailed': {
    AppLanguage.simplifiedChinese: '{name} 恢复失败：{reason}',
    AppLanguage.traditionalChinese: '{name} 恢復失敗：{reason}',
    AppLanguage.english: 'Failed to recover {name}: {reason}',
    AppLanguage.japanese: '{name} の復旧に失敗しました：{reason}',
  },
  'adminAutoDetectRecoveryFailedWithResult': {
    AppLanguage.simplifiedChinese: '{name} 恢复失败：{reason}（{result}）',
    AppLanguage.traditionalChinese: '{name} 恢復失敗：{reason}（{result}）',
    AppLanguage.english: 'Failed to recover {name}: {reason} ({result})',
    AppLanguage.japanese: '{name} の復旧に失敗しました：{reason}（{result}）',
  },
  'adminAutoDetectDeviceRecoveryPending': {
    AppLanguage.simplifiedChinese: '当前设备的恢复处理尚未接入',
    AppLanguage.traditionalChinese: '目前設備的恢復處理尚未接入',
    AppLanguage.english:
        'Recovery support for this device is not connected yet',
    AppLanguage.japanese: 'このデバイスの復旧処理は未接続です',
  },
  'adminAutoDetectStreamRetrying': {
    AppLanguage.simplifiedChinese: '推流重试中...',
    AppLanguage.traditionalChinese: '串流重試中...',
    AppLanguage.english: 'Retrying stream...',
    AppLanguage.japanese: 'ストリームを再試行中...',
  },
  'adminAutoDetectRetryStream': {
    AppLanguage.simplifiedChinese: '立即重试推流',
    AppLanguage.traditionalChinese: '立即重試串流',
    AppLanguage.english: 'Retry Stream Now',
    AppLanguage.japanese: '今すぐストリームを再試行',
  },
  'adminAutoDetectDeviceChecking': {
    AppLanguage.simplifiedChinese: '检测中...',
    AppLanguage.traditionalChinese: '檢測中...',
    AppLanguage.english: 'Checking...',
    AppLanguage.japanese: '検出中...',
  },
  'adminAutoDetectRecheckDevice': {
    AppLanguage.simplifiedChinese: '重新检测该设备',
    AppLanguage.traditionalChinese: '重新檢測該設備',
    AppLanguage.english: 'Recheck Device',
    AppLanguage.japanese: 'デバイスを再検出',
  },
  'adminAutoDetectAutomaticRecoveryUnsupported': {
    AppLanguage.simplifiedChinese: '暂不支持自动恢复',
    AppLanguage.traditionalChinese: '暫不支援自動恢復',
    AppLanguage.english: 'Automatic Recovery Unavailable',
    AppLanguage.japanese: '自動復旧は利用できません',
  },
  'adminAutoDetectRetryStreamTooltip': {
    AppLanguage.simplifiedChinese: '仅重新启动当前摄像头的视频推流，并在完成后复检',
    AppLanguage.traditionalChinese: '僅重新啟動目前攝影機的視訊串流，並在完成後複檢',
    AppLanguage.english:
        'Restart only the selected camera stream, then check it again',
    AppLanguage.japanese: '選択中のカメラストリームだけを再起動し、完了後に再検出します',
  },
  'adminAutoDetectRecheckTooltip': {
    AppLanguage.simplifiedChinese: '仅重新检测当前左侧选中的设备',
    AppLanguage.traditionalChinese: '僅重新檢測目前左側選中的設備',
    AppLanguage.english: 'Recheck only the device selected on the left',
    AppLanguage.japanese: '左側で選択中のデバイスだけを再検出します',
  },
  'adminAutoDetectOperationFailedDetail': {
    AppLanguage.simplifiedChinese: '设备操作未完成，请重试',
    AppLanguage.traditionalChinese: '設備操作未完成，請重試',
    AppLanguage.english: 'The device operation did not complete. Try again.',
    AppLanguage.japanese: 'デバイス操作が完了しませんでした。もう一度お試しください',
  },
  'adminAutoDetectLatestResultMissing': {
    AppLanguage.simplifiedChinese: '未找到 {name} 的最新检测结果',
    AppLanguage.traditionalChinese: '找不到 {name} 的最新檢測結果',
    AppLanguage.english: 'No latest detection result was found for {name}',
    AppLanguage.japanese: '{name} の最新検出結果が見つかりません',
  },
};
