import 'package:smart_cabinet/src/app/localization/app_localizations.dart';

const adminLocalizations = {
  'adminLoginTitle': {
    AppLanguage.simplifiedChinese: '管理员后台',
    AppLanguage.traditionalChinese: '管理員後台',
    AppLanguage.english: 'Admin Console',
    AppLanguage.japanese: '管理者コンソール',
  },
  'adminUsernameLabel': {
    AppLanguage.simplifiedChinese: '用户名',
    AppLanguage.traditionalChinese: '使用者名稱',
    AppLanguage.english: 'Username',
    AppLanguage.japanese: 'ユーザー名',
  },
  'adminPasswordLabel': {
    AppLanguage.simplifiedChinese: '密码',
    AppLanguage.traditionalChinese: '密碼',
    AppLanguage.english: 'Password',
    AppLanguage.japanese: 'パスワード',
  },
  'adminRememberPassword': {
    AppLanguage.simplifiedChinese: '记住密码',
    AppLanguage.traditionalChinese: '記住密碼',
    AppLanguage.english: 'Remember Password',
    AppLanguage.japanese: 'パスワードを記憶',
  },
  'adminLoginButton': {
    AppLanguage.simplifiedChinese: '登录',
    AppLanguage.traditionalChinese: '登入',
    AppLanguage.english: 'Log In',
    AppLanguage.japanese: 'ログイン',
  },
  'adminLoginDeniedMessage': {
    AppLanguage.simplifiedChinese: '账号或密码错误，或没有管理员权限',
    AppLanguage.traditionalChinese: '帳號或密碼錯誤，或沒有管理員權限',
    AppLanguage.english:
        'The account or password is incorrect, or admin permission is missing',
    AppLanguage.japanese: 'アカウントまたはパスワードが正しくないか、管理者権限がありません',
  },
  'adminLoginFailureMessage': {
    AppLanguage.simplifiedChinese: '管理员权限校验失败，请稍后重试',
    AppLanguage.traditionalChinese: '管理員權限校驗失敗，請稍後重試',
    AppLanguage.english:
        'Admin permission check failed. Please try again later',
    AppLanguage.japanese: '管理者権限の確認に失敗しました。後でもう一度お試しください',
  },
  'adminInputUsername': {
    AppLanguage.simplifiedChinese: '输入用户名',
    AppLanguage.traditionalChinese: '輸入使用者名稱',
    AppLanguage.english: 'Enter username',
    AppLanguage.japanese: 'ユーザー名を入力',
  },
  'adminInputPassword': {
    AppLanguage.simplifiedChinese: '输入密码',
    AppLanguage.traditionalChinese: '輸入密碼',
    AppLanguage.english: 'Enter password',
    AppLanguage.japanese: 'パスワードを入力',
  },
  'adminVerificationTitle': {
    AppLanguage.simplifiedChinese: '管理员身份校验',
    AppLanguage.traditionalChinese: '管理員身份校驗',
    AppLanguage.english: 'Admin Identity Verification',
    AppLanguage.japanese: '管理者本人確認',
  },
  'adminVerificationBadge': {
    AppLanguage.simplifiedChinese: '身份校验中 · 管理员',
    AppLanguage.traditionalChinese: '身份校驗中 · 管理員',
    AppLanguage.english: 'Verifying · Admin',
    AppLanguage.japanese: '確認中 · 管理者',
  },
  'adminVerificationHeading': {
    AppLanguage.simplifiedChinese: '请完成管理员安全身份认证',
    AppLanguage.traditionalChinese: '請完成管理員安全身份認證',
    AppLanguage.english: 'Complete admin security verification',
    AppLanguage.japanese: '管理者セキュリティ確認を完了してください',
  },
  'adminVerificationDescription': {
    AppLanguage.simplifiedChinese: '登录权限已通过，请继续完成人脸、指纹与 NFC 三项校验',
    AppLanguage.traditionalChinese: '登入權限已通過，請繼續完成人臉、指紋與 NFC 三項校驗',
    AppLanguage.english:
        'Login permission passed. Continue face, fingerprint, and NFC checks',
    AppLanguage.japanese: 'ログイン権限確認済み。顔、指紋、NFC確認を続行してください',
  },
  'adminVerificationProgress': {
    AppLanguage.simplifiedChinese: '已完成 {count} / 3 项认证',
    AppLanguage.traditionalChinese: '已完成 {count} / 3 項認證',
    AppLanguage.english: '{count} / 3 checks completed',
    AppLanguage.japanese: '{count} / 3 件完了',
  },
  'adminConsoleTitle': {
    AppLanguage.simplifiedChinese: '管理员控制台',
    AppLanguage.traditionalChinese: '管理員控制台',
    AppLanguage.english: 'Admin Console',
    AppLanguage.japanese: '管理者コンソール',
  },
  'adminConsoleBadge': {
    AppLanguage.simplifiedChinese: '设备管理 · 管理员',
    AppLanguage.traditionalChinese: '設備管理 · 管理員',
    AppLanguage.english: 'Device Management · Admin',
    AppLanguage.japanese: 'デバイス管理 · 管理者',
  },
  'adminDevicePanelTitle': {
    AppLanguage.simplifiedChinese: '当前柜体所有信息',
    AppLanguage.traditionalChinese: '目前櫃體所有資訊',
    AppLanguage.english: 'Current Cabinet Information',
    AppLanguage.japanese: '現在のキャビネット情報',
  },
  'adminDevicePanelSubtitle': {
    AppLanguage.simplifiedChinese: '柜体、网络、摄像头、NFC 与外设状态',
    AppLanguage.traditionalChinese: '櫃體、網路、攝影機、NFC 與外設狀態',
    AppLanguage.english: 'Cabinet, network, camera, NFC, and peripheral status',
    AppLanguage.japanese: 'キャビネット、ネットワーク、カメラ、NFC、周辺機器の状態',
  },
  'adminDeviceCabinetCode': {
    AppLanguage.simplifiedChinese: '柜体编号',
    AppLanguage.traditionalChinese: '櫃體編號',
    AppLanguage.english: 'Cabinet Code',
    AppLanguage.japanese: 'キャビネット番号',
  },
  'adminDeviceRegion': {
    AppLanguage.simplifiedChinese: '所在区域',
    AppLanguage.traditionalChinese: '所在區域',
    AppLanguage.english: 'Area',
    AppLanguage.japanese: 'エリア',
  },
  'adminDeviceRunningStatus': {
    AppLanguage.simplifiedChinese: '运行状态',
    AppLanguage.traditionalChinese: '運行狀態',
    AppLanguage.english: 'Running Status',
    AppLanguage.japanese: '稼働状態',
  },
  'adminDeviceWifi': {
    AppLanguage.simplifiedChinese: '连接 WiFi',
    AppLanguage.traditionalChinese: '連接 WiFi',
    AppLanguage.english: 'Connected WiFi',
    AppLanguage.japanese: '接続中の WiFi',
  },
  'adminDeviceRj45': {
    AppLanguage.simplifiedChinese: 'RJ45连接',
    AppLanguage.traditionalChinese: 'RJ45連接',
    AppLanguage.english: 'RJ45 Connection',
    AppLanguage.japanese: 'RJ45接続',
  },
  'adminDeviceCamera': {
    AppLanguage.simplifiedChinese: '摄像头',
    AppLanguage.traditionalChinese: '攝影機',
    AppLanguage.english: 'Camera',
    AppLanguage.japanese: 'カメラ',
  },
  'adminCameraFaceRecognition': {
    AppLanguage.simplifiedChinese: '人脸识别摄像头',
    AppLanguage.traditionalChinese: '人臉識別攝影機',
    AppLanguage.english: 'Face Recognition Camera',
    AppLanguage.japanese: '顔認証カメラ',
  },
  'adminCameraOutsideEnvironment': {
    AppLanguage.simplifiedChinese: '柜外环境摄像头',
    AppLanguage.traditionalChinese: '櫃外環境攝影機',
    AppLanguage.english: 'Outside Environment Camera',
    AppLanguage.japanese: '柜外環境カメラ',
  },
  'adminCameraOperationArea': {
    AppLanguage.simplifiedChinese: '操作区摄像头',
    AppLanguage.traditionalChinese: '操作區攝影機',
    AppLanguage.english: 'Operation Area Camera',
    AppLanguage.japanese: '操作エリアカメラ',
  },
  'adminCameraCertificateCapture': {
    AppLanguage.simplifiedChinese: '合格证采集摄像头',
    AppLanguage.traditionalChinese: '合格證採集攝影機',
    AppLanguage.english: 'Certificate Capture Camera',
    AppLanguage.japanese: '合格証撮影カメラ',
  },
  'adminDeviceNfc': {
    AppLanguage.simplifiedChinese: 'NFC',
    AppLanguage.traditionalChinese: 'NFC',
    AppLanguage.english: 'NFC',
    AppLanguage.japanese: 'NFC',
  },
  'adminDeviceFingerprint': {
    AppLanguage.simplifiedChinese: '指纹模块',
    AppLanguage.traditionalChinese: '指紋模組',
    AppLanguage.english: 'Fingerprint Module',
    AppLanguage.japanese: '指紋モジュール',
  },
  'adminDeviceCabinetBoard': {
    AppLanguage.simplifiedChinese: '柜控板',
    AppLanguage.traditionalChinese: '櫃控板',
    AppLanguage.english: 'Cabinet Control Board',
    AppLanguage.japanese: 'キャビネット制御ボード',
  },
  'adminDeviceScanner': {
    AppLanguage.simplifiedChinese: '扫码器',
    AppLanguage.traditionalChinese: '掃碼器',
    AppLanguage.english: 'Scanner',
    AppLanguage.japanese: 'スキャナー',
  },
  'adminFunctionPanelTitle': {
    AppLanguage.simplifiedChinese: '功能列表',
    AppLanguage.traditionalChinese: '功能列表',
    AppLanguage.english: 'Function List',
    AppLanguage.japanese: '機能リスト',
  },
  'adminFunctionPanelSubtitle': {
    AppLanguage.simplifiedChinese: '设备检测与维护入口',
    AppLanguage.traditionalChinese: '設備檢測與維護入口',
    AppLanguage.english: 'Device diagnostics and maintenance actions',
    AppLanguage.japanese: 'デバイス診断とメンテナンス',
  },
  'adminFunctionInitializeData': {
    AppLanguage.simplifiedChinese: '初始化数据',
    AppLanguage.traditionalChinese: '初始化資料',
    AppLanguage.english: 'Initialize Data',
    AppLanguage.japanese: 'データ初期化',
  },
  'adminFunctionInitializeDataDescription': {
    AppLanguage.simplifiedChinese: '清理本地演示数据并重新拉取柜体配置',
    AppLanguage.traditionalChinese: '清理本機演示資料並重新拉取櫃體配置',
    AppLanguage.english:
        'Clear local demo data and reload cabinet configuration',
    AppLanguage.japanese: 'ローカルデモデータを削除し、キャビネット設定を再取得します',
  },
  'adminFunctionResetDevice': {
    AppLanguage.simplifiedChinese: '重置设备',
    AppLanguage.traditionalChinese: '重置設備',
    AppLanguage.english: 'Reset Device',
    AppLanguage.japanese: 'デバイスをリセット',
  },
  'adminFunctionResetDeviceDescription': {
    AppLanguage.simplifiedChinese: '重启外设连接、柜控板与终端运行状态',
    AppLanguage.traditionalChinese: '重啟外設連接、櫃控板與終端運行狀態',
    AppLanguage.english:
        'Restart peripherals, cabinet board, and terminal runtime state',
    AppLanguage.japanese: '周辺機器、制御ボード、端末稼働状態を再起動します',
  },
  'adminFunctionAutoDetect': {
    AppLanguage.simplifiedChinese: '自动检测',
    AppLanguage.traditionalChinese: '自動檢測',
    AppLanguage.english: 'Auto Detect',
    AppLanguage.japanese: '自動検出',
  },
  'adminFunctionAutoDetectDescription': {
    AppLanguage.simplifiedChinese: '自动检查网络、摄像头、NFC、柜控板与扫码器',
    AppLanguage.traditionalChinese: '自動檢查網路、攝影機、NFC、櫃控板與掃碼器',
    AppLanguage.english:
        'Check network, camera, NFC, cabinet board, and scanner automatically',
    AppLanguage.japanese: 'ネットワーク、カメラ、NFC、制御ボード、スキャナーを自動確認します',
  },
  'adminAutoDetectTitle': {
    AppLanguage.simplifiedChinese: '自动检测',
    AppLanguage.traditionalChinese: '自動檢測',
    AppLanguage.english: 'Automatic Detection',
    AppLanguage.japanese: '自動検出',
  },
  'adminAutoDetectSubtitle': {
    AppLanguage.simplifiedChinese: '按状态筛选并选择左侧项目查看设备详情',
    AppLanguage.traditionalChinese: '按狀態篩選並選擇左側項目查看設備詳情',
    AppLanguage.english: 'Filter by status and select an item for details',
    AppLanguage.japanese: '状態で絞り込み、左側の項目を選択して詳細を確認します',
  },
  'adminAutoDetectItemsTitle': {
    AppLanguage.simplifiedChinese: '检测项目',
    AppLanguage.traditionalChinese: '檢測項目',
    AppLanguage.english: 'Detection Items',
    AppLanguage.japanese: '検出項目',
  },
  'adminAutoDetectItemDescription': {
    AppLanguage.simplifiedChinese: '检查 {name} 的连接状态与运行结果',
    AppLanguage.traditionalChinese: '檢查 {name} 的連接狀態與運行結果',
    AppLanguage.english: 'Check the connection and operating status of {name}',
    AppLanguage.japanese: '{name} の接続状態と動作結果を確認します',
  },
  'adminAutoDetectEmpty': {
    AppLanguage.simplifiedChinese: '暂无检测项',
    AppLanguage.traditionalChinese: '暫無檢測項',
    AppLanguage.english: 'No detection items',
    AppLanguage.japanese: '検出項目がありません',
  },
  'adminAutoDetectFilteredEmpty': {
    AppLanguage.simplifiedChinese: '当前筛选条件下暂无检测项',
    AppLanguage.traditionalChinese: '目前篩選條件下暫無檢測項',
    AppLanguage.english: 'No items match the current filter',
    AppLanguage.japanese: '現在の絞り込み条件に一致する項目はありません',
  },
  'adminAutoDetectCurrentResult': {
    AppLanguage.simplifiedChinese: '当前检测结果',
    AppLanguage.traditionalChinese: '目前檢測結果',
    AppLanguage.english: 'Current Result',
    AppLanguage.japanese: '現在の検出結果',
  },
  'adminAutoDetectAllCount': {
    AppLanguage.simplifiedChinese: '全部',
    AppLanguage.traditionalChinese: '全部',
    AppLanguage.english: 'All',
    AppLanguage.japanese: 'すべて',
  },
  'adminAutoDetectHealthyCount': {
    AppLanguage.simplifiedChinese: '正常',
    AppLanguage.traditionalChinese: '正常',
    AppLanguage.english: 'Healthy',
    AppLanguage.japanese: '正常',
  },
  'adminAutoDetectAbnormalCount': {
    AppLanguage.simplifiedChinese: '异常',
    AppLanguage.traditionalChinese: '異常',
    AppLanguage.english: 'Abnormal',
    AppLanguage.japanese: '異常',
  },
  'adminAutoDetectPendingCount': {
    AppLanguage.simplifiedChinese: '待接入',
    AppLanguage.traditionalChinese: '待接入',
    AppLanguage.english: 'Pending',
    AppLanguage.japanese: '未接続',
  },
  'adminAutoDetectStatusChecking': {
    AppLanguage.simplifiedChinese: '检测中',
    AppLanguage.traditionalChinese: '檢測中',
    AppLanguage.english: 'Checking',
    AppLanguage.japanese: '検出中',
  },
  'adminAutoDetectStatusHealthy': {
    AppLanguage.simplifiedChinese: '正常',
    AppLanguage.traditionalChinese: '正常',
    AppLanguage.english: 'Healthy',
    AppLanguage.japanese: '正常',
  },
  'adminAutoDetectStatusAbnormal': {
    AppLanguage.simplifiedChinese: '异常',
    AppLanguage.traditionalChinese: '異常',
    AppLanguage.english: 'Abnormal',
    AppLanguage.japanese: '異常',
  },
  'adminAutoDetectStatusPending': {
    AppLanguage.simplifiedChinese: '待接入',
    AppLanguage.traditionalChinese: '待接入',
    AppLanguage.english: 'Pending',
    AppLanguage.japanese: '未接続',
  },
  'adminAutoDetectCheckingResult': {
    AppLanguage.simplifiedChinese: '正在读取设备状态...',
    AppLanguage.traditionalChinese: '正在讀取設備狀態...',
    AppLanguage.english: 'Reading device status...',
    AppLanguage.japanese: 'デバイス状態を読み取り中...',
  },
  'adminAutoDetectConnected': {
    AppLanguage.simplifiedChinese: '连接成功',
    AppLanguage.traditionalChinese: '連接成功',
    AppLanguage.english: 'Connected',
    AppLanguage.japanese: '接続済み',
  },
  'adminAutoDetectDisconnected': {
    AppLanguage.simplifiedChinese: '连接失败',
    AppLanguage.traditionalChinese: '連接失敗',
    AppLanguage.english: 'Connection failed',
    AppLanguage.japanese: '接続失敗',
  },
  'adminAutoDetectSelectedActionHint': {
    AppLanguage.simplifiedChinese: '恢复操作仅作用于当前选中设备',
    AppLanguage.traditionalChinese: '恢復操作僅作用於目前選中設備',
    AppLanguage.english: 'Recovery affects only the selected device',
    AppLanguage.japanese: '復旧操作は選択中のデバイスだけに適用されます',
  },
  'adminAutoDetectInitialLoadFailed': {
    AppLanguage.simplifiedChinese: '自动检测失败：{error}',
    AppLanguage.traditionalChinese: '自動檢測失敗：{error}',
    AppLanguage.english: 'Automatic detection failed: {error}',
    AppLanguage.japanese: '自動検出に失敗しました：{error}',
  },
  'adminAutoDetectReconnectDevice': {
    AppLanguage.simplifiedChinese: '重连该设备',
    AppLanguage.traditionalChinese: '重連該設備',
    AppLanguage.english: 'Reconnect Device',
    AppLanguage.japanese: 'このデバイスを再接続',
  },
  'adminAutoDetectReconnectHint': {
    AppLanguage.simplifiedChinese: '仅重连当前左侧选中的设备',
    AppLanguage.traditionalChinese: '僅重連目前左側選中的設備',
    AppLanguage.english: 'Reconnect only the device selected on the left',
    AppLanguage.japanese: '左側で選択中のデバイスだけを再接続します',
  },
  'adminAutoDetectReconnecting': {
    AppLanguage.simplifiedChinese: '重连中...',
    AppLanguage.traditionalChinese: '重連中...',
    AppLanguage.english: 'Reconnecting...',
    AppLanguage.japanese: '再接続中...',
  },
  'adminAutoDetectReconnectPending': {
    AppLanguage.simplifiedChinese: '{name} 的重连接口待接入',
    AppLanguage.traditionalChinese: '{name} 的重連接口待接入',
    AppLanguage.english: 'Reconnect support for {name} is not connected yet',
    AppLanguage.japanese: '{name} の再接続機能は未接続です',
  },
  'adminAutoDetectReconnectSucceeded': {
    AppLanguage.simplifiedChinese: '{name} 已完成重连',
    AppLanguage.traditionalChinese: '{name} 已完成重連',
    AppLanguage.english: '{name} reconnected successfully',
    AppLanguage.japanese: '{name} の再接続が完了しました',
  },
  'adminAutoDetectReconnectFailed': {
    AppLanguage.simplifiedChinese: '{name} 重连失败：{error}',
    AppLanguage.traditionalChinese: '{name} 重連失敗：{error}',
    AppLanguage.english: 'Failed to reconnect {name}: {error}',
    AppLanguage.japanese: '{name} の再接続に失敗しました：{error}',
  },
  'adminAutoDetectClose': {
    AppLanguage.simplifiedChinese: '关闭',
    AppLanguage.traditionalChinese: '關閉',
    AppLanguage.english: 'Close',
    AppLanguage.japanese: '閉じる',
  },
  'adminFunctionIndexTitle': {
    AppLanguage.simplifiedChinese: '{index}、{title}',
    AppLanguage.traditionalChinese: '{index}、{title}',
    AppLanguage.english: '{index}. {title}',
    AppLanguage.japanese: '{index}. {title}',
  },
  'adminFunctionPendingMessage': {
    AppLanguage.simplifiedChinese: '{name} 功能待接入真实设备接口',
    AppLanguage.traditionalChinese: '{name} 功能待接入真實設備接口',
    AppLanguage.english: '{name} will be connected to real device APIs later',
    AppLanguage.japanese: '{name} は後で実機 API に接続されます',
  },
};
