import '../app_localizations.dart';

const dropoffLocalizations = {
  'dropoffFlowTag': {
    AppLanguage.simplifiedChinese: '放件',
    AppLanguage.traditionalChinese: '放件',
    AppLanguage.english: 'Drop-off',
    AppLanguage.japanese: '保管',
  },
  'dropoffPersonVerificationTitle': {
    AppLanguage.simplifiedChinese: '放件人员认证',
    AppLanguage.traditionalChinese: '放件人員驗證',
    AppLanguage.english: 'Drop-off Identity Verification',
    AppLanguage.japanese: '保管者認証',
  },
  'dropoffPersonVerificationBadge': {
    AppLanguage.simplifiedChinese: '人员认证中 · 放件',
    AppLanguage.traditionalChinese: '人員驗證中 · 放件',
    AppLanguage.english: 'Identity Verification · Drop-off',
    AppLanguage.japanese: '本人認証中 · 保管',
  },
  'dropoffPersonVerificationHeading': {
    AppLanguage.simplifiedChinese: '请完成存放人身份认证',
    AppLanguage.traditionalChinese: '請完成存放人身份驗證',
    AppLanguage.english: 'Please complete depositor identity verification',
    AppLanguage.japanese: '保管者の本人認証を完了してください',
  },
  'dropoffPersonVerificationProgress': {
    AppLanguage.simplifiedChinese: '已完成 {count} / 3 项认证',
    AppLanguage.traditionalChinese: '已完成 {count} / 3 項驗證',
    AppLanguage.english: '{count} / 3 verifications completed',
    AppLanguage.japanese: '{count} / 3 認証完了',
  },
  'dropoffFileVerificationTitle': {
    AppLanguage.simplifiedChinese: '文件认证',
    AppLanguage.traditionalChinese: '文件驗證',
    AppLanguage.english: 'Document Verification',
    AppLanguage.japanese: '文書認証',
  },
  'dropoffFileVerificationBadge': {
    AppLanguage.simplifiedChinese: '文件认证中 · 放件',
    AppLanguage.traditionalChinese: '文件驗證中 · 放件',
    AppLanguage.english: 'Document Verification · Drop-off',
    AppLanguage.japanese: '文書認証中 · 保管',
  },
  'dropoffImageFrontNormal': {
    AppLanguage.simplifiedChinese: '正面常规图',
    AppLanguage.traditionalChinese: '正面常規圖',
    AppLanguage.english: 'Front Standard Image',
    AppLanguage.japanese: '表面通常画像',
  },
  'dropoffImageFrontUv': {
    AppLanguage.simplifiedChinese: '正面紫外荧光图',
    AppLanguage.traditionalChinese: '正面紫外螢光圖',
    AppLanguage.english: 'Front UV Fluorescence Image',
    AppLanguage.japanese: '表面紫外蛍光画像',
  },
  'dropoffImageBackNormal': {
    AppLanguage.simplifiedChinese: '反面常规图',
    AppLanguage.traditionalChinese: '反面常規圖',
    AppLanguage.english: 'Back Standard Image',
    AppLanguage.japanese: '裏面通常画像',
  },
  'dropoffFlipHint': {
    AppLanguage.simplifiedChinese: '请翻转文件，保持放在识别区',
    AppLanguage.traditionalChinese: '請翻轉文件，並保持放在識別區',
    AppLanguage.english:
        'Please turn the document over and keep it in the scan area',
    AppLanguage.japanese: '文書を裏返し、認識エリアに置いたままにしてください',
  },
  'dropoffPlaceFileHint': {
    AppLanguage.simplifiedChinese: '请将文件放到指定识别区',
    AppLanguage.traditionalChinese: '請將文件放到指定識別區',
    AppLanguage.english: 'Place the document in the designated scan area',
    AppLanguage.japanese: '文書を指定の認識エリアに置いてください',
  },
  'dropoffStartRecognitionHint': {
    AppLanguage.simplifiedChinese: '点击开始识别后，系统将依次采集合格证正面常规图、正面紫外荧光图和反面常规图。',
    AppLanguage.traditionalChinese: '點擊開始識別後，系統將依序採集合格證正面常規圖、正面紫外螢光圖與反面常規圖。',
    AppLanguage.english:
        'After starting recognition, the system will capture the front standard image, front UV fluorescence image, and back standard image in sequence.',
    AppLanguage.japanese: '認識開始後、表面通常画像、表面紫外蛍光画像、裏面通常画像を順番に取得します。',
  },
  'dropoffImageCaptured': {
    AppLanguage.simplifiedChinese: '图像已采集',
    AppLanguage.traditionalChinese: '圖像已採集',
    AppLanguage.english: 'Image Captured',
    AppLanguage.japanese: '画像取得済み',
  },
  'dropoffCapturing': {
    AppLanguage.simplifiedChinese: '采集中...',
    AppLanguage.traditionalChinese: '採集中...',
    AppLanguage.english: 'Capturing...',
    AppLanguage.japanese: '取得中...',
  },
  'dropoffStartRecognition': {
    AppLanguage.simplifiedChinese: '开始识别',
    AppLanguage.traditionalChinese: '開始識別',
    AppLanguage.english: 'Start Recognition',
    AppLanguage.japanese: '認識開始',
  },
  'dropoffFrcTitle': {
    AppLanguage.simplifiedChinese: 'FRC 文件识别',
    AppLanguage.traditionalChinese: 'FRC 文件識別',
    AppLanguage.english: 'FRC Document Recognition',
    AppLanguage.japanese: 'FRC 文書認識',
  },
  'dropoffRecognitionStatusLabel': {
    AppLanguage.simplifiedChinese: '识别状态',
    AppLanguage.traditionalChinese: '識別狀態',
    AppLanguage.english: 'Recognition Status',
    AppLanguage.japanese: '認識状態',
  },
  'dropoffFrcRecognized': {
    AppLanguage.simplifiedChinese: 'FRC 已识别',
    AppLanguage.traditionalChinese: 'FRC 已識別',
    AppLanguage.english: 'FRC Recognized',
    AppLanguage.japanese: 'FRC 認識済み',
  },
  'dropoffWaitingFilePlaced': {
    AppLanguage.simplifiedChinese: '等待文件放入',
    AppLanguage.traditionalChinese: '等待文件放入',
    AppLanguage.english: 'Waiting for Document',
    AppLanguage.japanese: '文書待機中',
  },
  'dropoffFileCodeLabel': {
    AppLanguage.simplifiedChinese: '文件编号',
    AppLanguage.traditionalChinese: '文件編號',
    AppLanguage.english: 'Document Code',
    AppLanguage.japanese: '文書番号',
  },
  'dropoffFileNameLabel': {
    AppLanguage.simplifiedChinese: '文件名称',
    AppLanguage.traditionalChinese: '文件名稱',
    AppLanguage.english: 'Document Name',
    AppLanguage.japanese: '文書名',
  },
  'dropoffMatchResultLabel': {
    AppLanguage.simplifiedChinese: '匹配结果',
    AppLanguage.traditionalChinese: '匹配結果',
    AppLanguage.english: 'Match Result',
    AppLanguage.japanese: '照合結果',
  },
  'dropoffMatched': {
    AppLanguage.simplifiedChinese: '已匹配',
    AppLanguage.traditionalChinese: '已匹配',
    AppLanguage.english: 'Matched',
    AppLanguage.japanese: '一致',
  },
  'dropoffPendingMatch': {
    AppLanguage.simplifiedChinese: '待匹配',
    AppLanguage.traditionalChinese: '待匹配',
    AppLanguage.english: 'Pending Match',
    AppLanguage.japanese: '照合待ち',
  },
  'dropoffTagReadHint': {
    AppLanguage.simplifiedChinese: '文件标签已读取，等待图像采集完成。',
    AppLanguage.traditionalChinese: '文件標籤已讀取，等待圖像採集完成。',
    AppLanguage.english:
        'Document tag read. Waiting for image capture to complete.',
    AppLanguage.japanese: '文書タグを読み取りました。画像取得完了を待機しています。',
  },
  'dropoffPlaceFileForFrcHint': {
    AppLanguage.simplifiedChinese: '请将文件放入识别区，FRC 将自动检测。',
    AppLanguage.traditionalChinese: '請將文件放入識別區，FRC 將自動檢測。',
    AppLanguage.english:
        'Place the document in the scan area. FRC will detect it automatically.',
    AppLanguage.japanese: '文書を認識エリアに置いてください。FRC が自動検出します。',
  },
  'dropoffImageNotCaptured': {
    AppLanguage.simplifiedChinese: '未采集',
    AppLanguage.traditionalChinese: '未採集',
    AppLanguage.english: 'Not Captured',
    AppLanguage.japanese: '未取得',
  },
  'dropoffImageCapturedSuffix': {
    AppLanguage.simplifiedChinese: '{title}已采集',
    AppLanguage.traditionalChinese: '{title}已採集',
    AppLanguage.english: '{title} Captured',
    AppLanguage.japanese: '{title} 取得済み',
  },
  'dropoffConfirmTitle': {
    AppLanguage.simplifiedChinese: '放件信息确认',
    AppLanguage.traditionalChinese: '放件資訊確認',
    AppLanguage.english: 'Drop-off Confirmation',
    AppLanguage.japanese: '保管情報確認',
  },
  'dropoffConfirmBadge': {
    AppLanguage.simplifiedChinese: '认证完成 · 待开柜',
    AppLanguage.traditionalChinese: '驗證完成 · 待開櫃',
    AppLanguage.english: 'Verified · Awaiting Door Open',
    AppLanguage.japanese: '認証完了 · 開扉待機',
  },
  'dropoffOpeningHint': {
    AppLanguage.simplifiedChinese: '认证完成，柜门即将打开...',
    AppLanguage.traditionalChinese: '驗證完成，櫃門即將開啟...',
    AppLanguage.english:
        'Verification complete. The cabinet door will open shortly...',
    AppLanguage.japanese: '認証完了。まもなく扉が開きます...',
  },
  'dropoffOpeningCountdown': {
    AppLanguage.simplifiedChinese: '{seconds}s 后自动打开柜门',
    AppLanguage.traditionalChinese: '{seconds}s 後自動開啟櫃門',
    AppLanguage.english: 'Door opens automatically in {seconds}s',
    AppLanguage.japanese: '{seconds} 秒後に自動で扉を開きます',
  },
  'dropoffDepositorInfo': {
    AppLanguage.simplifiedChinese: '存放人信息',
    AppLanguage.traditionalChinese: '存放人資訊',
    AppLanguage.english: 'Depositor Information',
    AppLanguage.japanese: '保管者情報',
  },
  'dropoffNameLabel': {
    AppLanguage.simplifiedChinese: '姓名',
    AppLanguage.traditionalChinese: '姓名',
    AppLanguage.english: 'Name',
    AppLanguage.japanese: '氏名',
  },
  'dropoffEmployeeCodeLabel': {
    AppLanguage.simplifiedChinese: '工号',
    AppLanguage.traditionalChinese: '工號',
    AppLanguage.english: 'Employee ID',
    AppLanguage.japanese: '社員番号',
  },
  'dropoffDepartmentLabel': {
    AppLanguage.simplifiedChinese: '部门',
    AppLanguage.traditionalChinese: '部門',
    AppLanguage.english: 'Department',
    AppLanguage.japanese: '部門',
  },
  'dropoffPermissionLabel': {
    AppLanguage.simplifiedChinese: '权限',
    AppLanguage.traditionalChinese: '權限',
    AppLanguage.english: 'Permission',
    AppLanguage.japanese: '権限',
  },
  'dropoffVerificationLabel': {
    AppLanguage.simplifiedChinese: '认证',
    AppLanguage.traditionalChinese: '驗證',
    AppLanguage.english: 'Verification',
    AppLanguage.japanese: '認証',
  },
  'dropoffVerificationPassed': {
    AppLanguage.simplifiedChinese: '人脸/指纹/NFC 已通过',
    AppLanguage.traditionalChinese: '人臉/指紋/NFC 已通過',
    AppLanguage.english: 'Face / Fingerprint / NFC verified',
    AppLanguage.japanese: '顔 / 指紋 / NFC 認証済み',
  },
  'dropoffDocumentInfo': {
    AppLanguage.simplifiedChinese: '文件信息',
    AppLanguage.traditionalChinese: '文件資訊',
    AppLanguage.english: 'Document Information',
    AppLanguage.japanese: '文書情報',
  },
  'dropoffFrcLabel': {
    AppLanguage.simplifiedChinese: 'FRC识别',
    AppLanguage.traditionalChinese: 'FRC識別',
    AppLanguage.english: 'FRC Recognition',
    AppLanguage.japanese: 'FRC 認識',
  },
  'dropoffDoorInfoTitle': {
    AppLanguage.simplifiedChinese: '柜门信息',
    AppLanguage.traditionalChinese: '櫃門資訊',
    AppLanguage.english: 'Cabinet Door Information',
    AppLanguage.japanese: '扉情報',
  },
  'dropoffOpenCabinetTitle': {
    AppLanguage.simplifiedChinese: '放入文件',
    AppLanguage.traditionalChinese: '放入文件',
    AppLanguage.english: 'Place Document',
    AppLanguage.japanese: '文書を入れる',
  },
  'dropoffOpenCabinetBadge': {
    AppLanguage.simplifiedChinese: '柜门已打开 · 放件',
    AppLanguage.traditionalChinese: '櫃門已開啟 · 放件',
    AppLanguage.english: 'Door Opened · Drop-off',
    AppLanguage.japanese: '扉開放中 · 保管',
  },
  'dropoffPlaceDocumentHint': {
    AppLanguage.simplifiedChinese: '请将文件放入柜门并关闭',
    AppLanguage.traditionalChinese: '請將文件放入櫃門並關閉',
    AppLanguage.english: 'Place the document in the cabinet and close the door',
    AppLanguage.japanese: '文書を入れて扉を閉めてください',
  },
  'dropoffAuditHint': {
    AppLanguage.simplifiedChinese: '系统将记录本次放件审计日志',
    AppLanguage.traditionalChinese: '系統將記錄本次放件審計日誌',
    AppLanguage.english:
        'The system will record an audit log for this drop-off',
    AppLanguage.japanese: '今回の保管操作は監査ログに記録されます',
  },
  'dropoffCloseDoorButton': {
    AppLanguage.simplifiedChinese: '确认已关闭柜门',
    AppLanguage.traditionalChinese: '確認已關閉櫃門',
    AppLanguage.english: 'Confirm Door Closed',
    AppLanguage.japanese: '扉を閉めたことを確認',
  },
  'dropoffReopenDoorButton': {
    AppLanguage.simplifiedChinese: '重新开柜',
    AppLanguage.traditionalChinese: '重新開櫃',
    AppLanguage.english: 'Reopen Door',
    AppLanguage.japanese: '再度開扉',
  },
  'dropoffCompletedBadge': {
    AppLanguage.simplifiedChinese: '放件完成',
    AppLanguage.traditionalChinese: '放件完成',
    AppLanguage.english: 'Drop-off Complete',
    AppLanguage.japanese: '保管完了',
  },
  'dropoffSuccessTitle': {
    AppLanguage.simplifiedChinese: '放件成功',
    AppLanguage.traditionalChinese: '放件成功',
    AppLanguage.english: 'Drop-off Successful',
    AppLanguage.japanese: '保管完了',
  },
  'dropoffReturnHome': {
    AppLanguage.simplifiedChinese: '返回首页',
    AppLanguage.traditionalChinese: '返回首頁',
    AppLanguage.english: 'Back Home',
    AppLanguage.japanese: 'ホームへ戻る',
  },
  'dropoffContinue': {
    AppLanguage.simplifiedChinese: '继续放件',
    AppLanguage.traditionalChinese: '繼續放件',
    AppLanguage.english: 'Continue Drop-off',
    AppLanguage.japanese: '続けて保管',
  },
  'dropoffBack': {
    AppLanguage.simplifiedChinese: '返回',
    AppLanguage.traditionalChinese: '返回',
    AppLanguage.english: 'Back',
    AppLanguage.japanese: '戻る',
  },
};
