import '../app_localizations.dart';

const homeLocalizations = {
  'appTitle': {
    AppLanguage.simplifiedChinese: '智能文件保管柜',
    AppLanguage.traditionalChinese: '智能文件保管櫃',
    AppLanguage.english: 'Smart Document Cabinet',
    AppLanguage.japanese: 'スマート文書保管庫',
  },
  'currentCabinet': {
    AppLanguage.simplifiedChinese: '当前柜体',
    AppLanguage.traditionalChinese: '目前櫃體',
    AppLanguage.english: 'Current Cabinet',
    AppLanguage.japanese: '現在のキャビネット',
  },
  'cabinetCode': {
    AppLanguage.simplifiedChinese: '编号',
    AppLanguage.traditionalChinese: '編號',
    AppLanguage.english: 'Code',
    AppLanguage.japanese: '番号',
  },
  'cabinetRegion': {
    AppLanguage.simplifiedChinese: '区域',
    AppLanguage.traditionalChinese: '區域',
    AppLanguage.english: 'Area',
    AppLanguage.japanese: 'エリア',
  },
  'cabinetStatus': {
    AppLanguage.simplifiedChinese: '状态',
    AppLanguage.traditionalChinese: '狀態',
    AppLanguage.english: 'Status',
    AppLanguage.japanese: '状態',
  },
  'safeTip': {
    AppLanguage.simplifiedChinese: '安全提示',
    AppLanguage.traditionalChinese: '安全提示',
    AppLanguage.english: 'Safety Tip',
    AppLanguage.japanese: '安全通知',
  },
  'bannerSubtitle': {
    AppLanguage.simplifiedChinese: '存取流程优化 · 异常实时预警 · 全程安全追溯',
    AppLanguage.traditionalChinese: '存取流程優化 · 異常即時預警 · 全程安全追溯',
    AppLanguage.english: 'Optimized access · Live alerts · Full traceability',
    AppLanguage.japanese: '入出庫最適化 · リアルタイム警告 · 全程追跡',
  },
  'todayFlow': {
    AppLanguage.simplifiedChinese: '今日流转',
    AppLanguage.traditionalChinese: '今日流轉',
    AppLanguage.english: 'Today Flow',
    AppLanguage.japanese: '本日の処理',
  },
  'freeSlots': {
    AppLanguage.simplifiedChinese: '空闲格口',
    AppLanguage.traditionalChinese: '空閒格口',
    AppLanguage.english: 'Free Slots',
    AppLanguage.japanese: '空き区画',
  },
  'pending': {
    AppLanguage.simplifiedChinese: '待处理',
    AppLanguage.traditionalChinese: '待處理',
    AppLanguage.english: 'Pending',
    AppLanguage.japanese: '未処理',
  },
  'storageStats': {
    AppLanguage.simplifiedChinese: '存储统计',
    AppLanguage.traditionalChinese: '儲存統計',
    AppLanguage.english: 'Storage Stats',
    AppLanguage.japanese: '保管統計',
  },
  'cabinetFiles': {
    AppLanguage.simplifiedChinese: '柜内文件',
    AppLanguage.traditionalChinese: '櫃內文件',
    AppLanguage.english: 'Documents',
    AppLanguage.japanese: '文書数',
  },
  'usedSlots': {
    AppLanguage.simplifiedChinese: '已用格位',
    AppLanguage.traditionalChinese: '已用格位',
    AppLanguage.english: 'Used Slots',
    AppLanguage.japanese: '使用中区画',
  },
  'pendingPickup': {
    AppLanguage.simplifiedChinese: '待取件',
    AppLanguage.traditionalChinese: '待取件',
    AppLanguage.english: 'To Pick Up',
    AppLanguage.japanese: '受取待ち',
  },
  'todayStored': {
    AppLanguage.simplifiedChinese: '今日存入',
    AppLanguage.traditionalChinese: '今日存入',
    AppLanguage.english: 'Stored Today',
    AppLanguage.japanese: '本日保管',
  },
  'todayPickedUp': {
    AppLanguage.simplifiedChinese: '今日取出',
    AppLanguage.traditionalChinese: '今日取出',
    AppLanguage.english: 'Picked Today',
    AppLanguage.japanese: '本日受取',
  },
  'occupancyRate': {
    AppLanguage.simplifiedChinese: '格位占用率',
    AppLanguage.traditionalChinese: '格位占用率',
    AppLanguage.english: 'Occupancy',
    AppLanguage.japanese: '使用率',
  },
  'access': {
    AppLanguage.simplifiedChinese: '存取件',
    AppLanguage.traditionalChinese: '存取件',
    AppLanguage.english: 'Access',
    AppLanguage.japanese: '入出庫',
  },
  'accessDescription': {
    AppLanguage.simplifiedChinese: '进入存件 / 取件业务入口',
    AppLanguage.traditionalChinese: '進入存件 / 取件業務入口',
    AppLanguage.english: 'Start drop-off or pickup workflow',
    AppLanguage.japanese: '保管 / 受取業務を開始',
  },
  'start': {
    AppLanguage.simplifiedChinese: '开始办理',
    AppLanguage.traditionalChinese: '開始辦理',
    AppLanguage.english: 'Start',
    AppLanguage.japanese: '開始',
  },
  'inspection': {
    AppLanguage.simplifiedChinese: '飞检操作',
    AppLanguage.traditionalChinese: '飛檢操作',
    AppLanguage.english: 'Inspection',
    AppLanguage.japanese: '抜取検査',
  },
  'tapStart': {
    AppLanguage.simplifiedChinese: '点击开始 →',
    AppLanguage.traditionalChinese: '點擊開始 →',
    AppLanguage.english: 'Tap to start →',
    AppLanguage.japanese: 'タップして開始 →',
  },
  'adminMode': {
    AppLanguage.simplifiedChinese: '管理员模式',
    AppLanguage.traditionalChinese: '管理員模式',
    AppLanguage.english: 'Admin Mode',
    AppLanguage.japanese: '管理者モード',
  },
  'settings': {
    AppLanguage.simplifiedChinese: '设置',
    AppLanguage.traditionalChinese: '設定',
    AppLanguage.english: 'Settings',
    AppLanguage.japanese: '設定',
  },
  'settingsSubtitle': {
    AppLanguage.simplifiedChinese: '设备偏好与本地显示配置',
    AppLanguage.traditionalChinese: '設備偏好與本機顯示設定',
    AppLanguage.english: 'Device preferences and display options',
    AppLanguage.japanese: '端末設定と表示オプション',
  },
  'languageSetting': {
    AppLanguage.simplifiedChinese: '语言设置',
    AppLanguage.traditionalChinese: '語言設定',
    AppLanguage.english: 'Language',
    AppLanguage.japanese: '言語設定',
  },
  'languageSettingHint': {
    AppLanguage.simplifiedChinese: '选择终端界面显示语言',
    AppLanguage.traditionalChinese: '選擇終端介面顯示語言',
    AppLanguage.english: 'Choose terminal display language',
    AppLanguage.japanese: '端末画面の表示言語を選択',
  },
  'aboutDevice': {
    AppLanguage.simplifiedChinese: '关于设备',
    AppLanguage.traditionalChinese: '關於設備',
    AppLanguage.english: 'About Device',
    AppLanguage.japanese: 'デバイス情報',
  },
  'aboutDeviceHint': {
    AppLanguage.simplifiedChinese: '查看当前主板与系统信息',
    AppLanguage.traditionalChinese: '查看目前主板與系統資訊',
    AppLanguage.english: 'View current board and system information',
    AppLanguage.japanese: '現在の基板とシステム情報を表示',
  },
  'aboutDeviceLoadFailed': {
    AppLanguage.simplifiedChinese: '设备信息读取失败，请确认当前运行在 Android 主板环境',
    AppLanguage.traditionalChinese: '設備資訊讀取失敗，請確認目前執行於 Android 主板環境',
    AppLanguage.english:
        'Failed to read device information. Confirm this is running on the Android board.',
    AppLanguage.japanese: 'デバイス情報を取得できません。Android 基板環境で実行されているか確認してください。',
  },
  'close': {
    AppLanguage.simplifiedChinese: '关闭',
    AppLanguage.traditionalChinese: '關閉',
    AppLanguage.english: 'Close',
    AppLanguage.japanese: '閉じる',
  },
};
