import 'package:smart_cabinet/src/app/localization/app_localizations.dart';

const pickupLocalizations = {
  'pickupFlowTag': {
    AppLanguage.simplifiedChinese: '取件',
    AppLanguage.traditionalChinese: '取件',
    AppLanguage.english: 'Pickup',
    AppLanguage.japanese: '受取',
  },
  'pickupVerificationHeader': {
    AppLanguage.simplifiedChinese: '安全身份验证',
    AppLanguage.traditionalChinese: '安全身份驗證',
    AppLanguage.english: 'Security Verification',
    AppLanguage.japanese: '本人確認',
  },
  'pickupVerificationBadge': {
    AppLanguage.simplifiedChinese: '四重认证中 · 取件',
    AppLanguage.traditionalChinese: '四重驗證中 · 取件',
    AppLanguage.english: 'Four-Step Verification · Pickup',
    AppLanguage.japanese: '四重認証中 · 受取',
  },
  'pickupVerificationPassedBadge': {
    AppLanguage.simplifiedChinese: '四重认证通过 · 取件',
    AppLanguage.traditionalChinese: '四重驗證通過 · 取件',
    AppLanguage.english: 'Four-Step Verified · Pickup',
    AppLanguage.japanese: '四重認証完了 · 受取',
  },
  'pickupFaceTitle': {
    AppLanguage.simplifiedChinese: '人脸识别',
    AppLanguage.traditionalChinese: '人臉識別',
    AppLanguage.english: 'Face Recognition',
    AppLanguage.japanese: '顔認証',
  },
  'pickupFingerprintTitle': {
    AppLanguage.simplifiedChinese: '指纹识别',
    AppLanguage.traditionalChinese: '指紋識別',
    AppLanguage.english: 'Fingerprint Scan',
    AppLanguage.japanese: '指紋認証',
  },
  'pickupNfcTitle': {
    AppLanguage.simplifiedChinese: 'NFC识别',
    AppLanguage.traditionalChinese: 'NFC識別',
    AppLanguage.english: 'NFC Scan',
    AppLanguage.japanese: 'NFC認証',
  },
  'pickupCodeTitle': {
    AppLanguage.simplifiedChinese: '取件码',
    AppLanguage.traditionalChinese: '取件碼',
    AppLanguage.english: 'Pickup Code',
    AppLanguage.japanese: '受取コード',
  },
  'pickupConfirmFingerprint': {
    AppLanguage.simplifiedChinese: '确认指纹识别',
    AppLanguage.traditionalChinese: '確認指紋識別',
    AppLanguage.english: 'Confirm Fingerprint',
    AppLanguage.japanese: '指紋認証を確認',
  },
  'pickupFingerprintDone': {
    AppLanguage.simplifiedChinese: '指纹识别已完成',
    AppLanguage.traditionalChinese: '指紋識別已完成',
    AppLanguage.english: 'Fingerprint Verified',
    AppLanguage.japanese: '指紋認証完了',
  },
  'pickupConfirmNfc': {
    AppLanguage.simplifiedChinese: '确认NFC识别',
    AppLanguage.traditionalChinese: '確認NFC識別',
    AppLanguage.english: 'Confirm NFC',
    AppLanguage.japanese: 'NFC認証を確認',
  },
  'pickupNfcDone': {
    AppLanguage.simplifiedChinese: 'NFC识别已完成',
    AppLanguage.traditionalChinese: 'NFC識別已完成',
    AppLanguage.english: 'NFC Verified',
    AppLanguage.japanese: 'NFC認証完了',
  },
  'pickupBack': {
    AppLanguage.simplifiedChinese: '返回',
    AppLanguage.traditionalChinese: '返回',
    AppLanguage.english: 'Back',
    AppLanguage.japanese: '戻る',
  },
  'pickupCodeHint': {
    AppLanguage.simplifiedChinese: '请输入8位取件码',
    AppLanguage.traditionalChinese: '請輸入 8 位取件碼',
    AppLanguage.english: 'Enter 8-digit pickup code',
    AppLanguage.japanese: '8桁の受取コードを入力してください',
  },
  'pickupCodeVerified': {
    AppLanguage.simplifiedChinese: '取件码校验完成',
    AppLanguage.traditionalChinese: '取件碼校驗完成',
    AppLanguage.english: 'Pickup code verified',
    AppLanguage.japanese: '受取コード確認完了',
  },
  'pickupCodeProgress': {
    AppLanguage.simplifiedChinese: '已输入 {count} / 8 位',
    AppLanguage.traditionalChinese: '已輸入 {count} / 8 位',
    AppLanguage.english: '{count} / 8 entered',
    AppLanguage.japanese: '{count} / 8 入力済み',
  },
  'pickupVerificationProgress': {
    AppLanguage.simplifiedChinese: '验证进度',
    AppLanguage.traditionalChinese: '驗證進度',
    AppLanguage.english: 'Verification Progress',
    AppLanguage.japanese: '認証進捗',
  },
  'pickupActionClear': {
    AppLanguage.simplifiedChinese: '清空',
    AppLanguage.traditionalChinese: '清空',
    AppLanguage.english: 'Clear',
    AppLanguage.japanese: 'クリア',
  },
  'pickupActionDelete': {
    AppLanguage.simplifiedChinese: '删除',
    AppLanguage.traditionalChinese: '刪除',
    AppLanguage.english: 'Delete',
    AppLanguage.japanese: '削除',
  },
  'sharedVerificationProgress': {
    AppLanguage.simplifiedChinese: '验证进度',
    AppLanguage.traditionalChinese: '驗證進度',
    AppLanguage.english: 'Verification Progress',
    AppLanguage.japanese: '認証進捗',
  },
  'sharedWaitingVerification': {
    AppLanguage.simplifiedChinese: '等待认证',
    AppLanguage.traditionalChinese: '等待驗證',
    AppLanguage.english: 'Waiting for Verification',
    AppLanguage.japanese: '認証待機中',
  },
  'sharedVerified': {
    AppLanguage.simplifiedChinese: '已通过',
    AppLanguage.traditionalChinese: '已通過',
    AppLanguage.english: 'Verified',
    AppLanguage.japanese: '認証済み',
  },
  'sharedFaceCameraStarting': {
    AppLanguage.simplifiedChinese: '正在启动摄像头...',
    AppLanguage.traditionalChinese: '正在啟動攝像頭...',
    AppLanguage.english: 'Starting camera...',
    AppLanguage.japanese: 'カメラを起動中...',
  },
  'sharedFaceVerifiedSubmitted': {
    AppLanguage.simplifiedChinese: '人脸识别通过，照片已提交后端校验',
    AppLanguage.traditionalChinese: '人臉識別通過，照片已提交後端校驗',
    AppLanguage.english:
        'Face verified. Photo submitted for backend validation.',
    AppLanguage.japanese: '顔認証成功。写真をバックエンド検証へ送信しました。',
  },
  'sharedFaceNoCamera': {
    AppLanguage.simplifiedChinese: '未检测到可用摄像头',
    AppLanguage.traditionalChinese: '未檢測到可用攝像頭',
    AppLanguage.english: 'No camera detected',
    AppLanguage.japanese: '利用可能なカメラが見つかりません',
  },
  'sharedFaceCameraReady': {
    AppLanguage.simplifiedChinese: '摄像头已启动，请对准面部后点击确认',
    AppLanguage.traditionalChinese: '攝像頭已啟動，請對準臉部後點擊確認',
    AppLanguage.english: 'Camera ready. Align your face and tap confirm.',
    AppLanguage.japanese: 'カメラ準備完了。顔を合わせて確認を押してください。',
  },
  'sharedFaceCameraAccessDenied': {
    AppLanguage.simplifiedChinese: '摄像头权限被拒绝',
    AppLanguage.traditionalChinese: '攝像頭權限被拒絕',
    AppLanguage.english: 'Camera access denied',
    AppLanguage.japanese: 'カメラ権限が拒否されました',
  },
  'sharedFaceCameraPermanentlyDenied': {
    AppLanguage.simplifiedChinese: '摄像头权限被永久拒绝，请到系统设置开启',
    AppLanguage.traditionalChinese: '攝像頭權限被永久拒絕，請到系統設定開啟',
    AppLanguage.english:
        'Camera access permanently denied. Enable it in system settings.',
    AppLanguage.japanese: 'カメラ権限が恒久的に拒否されています。設定で有効にしてください。',
  },
  'sharedFaceCameraStartFailed': {
    AppLanguage.simplifiedChinese: '摄像头启动失败：{reason}',
    AppLanguage.traditionalChinese: '攝像頭啟動失敗：{reason}',
    AppLanguage.english: 'Camera start failed: {reason}',
    AppLanguage.japanese: 'カメラ起動失敗：{reason}',
  },
  'sharedFaceFallbackAllowed': {
    AppLanguage.simplifiedChinese: '{message}，可使用模拟校验',
    AppLanguage.traditionalChinese: '{message}，可使用模擬校驗',
    AppLanguage.english: '{message}. Simulated verification is available.',
    AppLanguage.japanese: '{message}。シミュレーション認証を利用できます。',
  },
  'sharedFaceCapturing': {
    AppLanguage.simplifiedChinese: '正在拍照并提交后端校验...',
    AppLanguage.traditionalChinese: '正在拍照並提交後端校驗...',
    AppLanguage.english:
        'Capturing photo and submitting for backend validation...',
    AppLanguage.japanese: '写真を撮影してバックエンド検証へ送信中...',
  },
  'sharedFaceCaptureFailed': {
    AppLanguage.simplifiedChinese: '拍照或校验失败：{reason}',
    AppLanguage.traditionalChinese: '拍照或校驗失敗：{reason}',
    AppLanguage.english: 'Photo capture or verification failed: {reason}',
    AppLanguage.japanese: '撮影または認証に失敗しました：{reason}',
  },
  'sharedFaceVerifiedShort': {
    AppLanguage.simplifiedChinese: '人脸识别通过',
    AppLanguage.traditionalChinese: '人臉識別通過',
    AppLanguage.english: 'Face Verified',
    AppLanguage.japanese: '顔認証成功',
  },
  'sharedFaceVerifying': {
    AppLanguage.simplifiedChinese: '校验中...',
    AppLanguage.traditionalChinese: '校驗中...',
    AppLanguage.english: 'Verifying...',
    AppLanguage.japanese: '検証中...',
  },
  'sharedFaceConfirmCapture': {
    AppLanguage.simplifiedChinese: '确认并拍照校验',
    AppLanguage.traditionalChinese: '確認並拍照校驗',
    AppLanguage.english: 'Confirm and Capture',
    AppLanguage.japanese: '確認して撮影認証',
  },
  'pickupLoadingTitle': {
    AppLanguage.simplifiedChinese: '验证成功，正在获取证据信息···',
    AppLanguage.traditionalChinese: '驗證成功，正在取得證據資訊···',
    AppLanguage.english: 'Verification succeeded, loading evidence...',
    AppLanguage.japanese: '認証成功、証跡情報を取得中...',
  },
  'pickupLoadingSubtitle': {
    AppLanguage.simplifiedChinese: '系统正在读取本次取件凭证、人员信息与柜门授权数据',
    AppLanguage.traditionalChinese: '系統正在讀取本次取件憑證、人員資訊與櫃門授權資料',
    AppLanguage.english:
        'Loading pickup credentials, identity details, and cabinet authorization data',
    AppLanguage.japanese: '受取資格情報、本人情報、キャビネット権限データを取得しています',
  },
  'pickupDoorInfoBadge': {
    AppLanguage.simplifiedChinese: '证据信息已获取 · 待开柜',
    AppLanguage.traditionalChinese: '證據資訊已取得 · 待開櫃',
    AppLanguage.english: 'Evidence Ready · Awaiting Open',
    AppLanguage.japanese: '証跡取得済み · 開扉待機',
  },
  'pickupDoorNoSectionTitle': {
    AppLanguage.simplifiedChinese: '柜门信息',
    AppLanguage.traditionalChinese: '櫃門資訊',
    AppLanguage.english: 'Cabinet Door Information',
    AppLanguage.japanese: '扉情報',
  },
  'pickupDoorAuthorizationInfo': {
    AppLanguage.simplifiedChinese: 'Door Authorization Information',
    AppLanguage.traditionalChinese: 'Door Authorization Information',
    AppLanguage.english: 'Door Authorization Information',
    AppLanguage.japanese: '扉認可情報',
  },
  'pickupDoorNoLabel': {
    AppLanguage.simplifiedChinese: '柜门编号',
    AppLanguage.traditionalChinese: '櫃門編號',
    AppLanguage.english: 'Cabinet Door',
    AppLanguage.japanese: '扉番号',
  },
  'pickupFileCountLabel': {
    AppLanguage.simplifiedChinese: '文件数量',
    AppLanguage.traditionalChinese: '文件數量',
    AppLanguage.english: 'File Count',
    AppLanguage.japanese: '文書数',
  },
  'pickupFileCountValue': {
    AppLanguage.simplifiedChinese: '1 份',
    AppLanguage.traditionalChinese: '1 份',
    AppLanguage.english: '1 file',
    AppLanguage.japanese: '1 件',
  },
  'pickupAuthorizationLabel': {
    AppLanguage.simplifiedChinese: '授权状态',
    AppLanguage.traditionalChinese: '授權狀態',
    AppLanguage.english: 'Authorization',
    AppLanguage.japanese: '認可状態',
  },
  'pickupAuthorizedValue': {
    AppLanguage.simplifiedChinese: '已授权',
    AppLanguage.traditionalChinese: '已授權',
    AppLanguage.english: 'Authorized',
    AppLanguage.japanese: '認可済み',
  },
  'pickupFileNameLabel': {
    AppLanguage.simplifiedChinese: '文件名称',
    AppLanguage.traditionalChinese: '文件名稱',
    AppLanguage.english: 'Document Name',
    AppLanguage.japanese: '文書名',
  },
  'pickupFileLevelLabel': {
    AppLanguage.simplifiedChinese: '文件密级',
    AppLanguage.traditionalChinese: '文件密級',
    AppLanguage.english: 'Security Level',
    AppLanguage.japanese: '文書機密区分',
  },
  'pickupFileLevelValue': {
    AppLanguage.simplifiedChinese: '内部机密 / 实名追溯',
    AppLanguage.traditionalChinese: '內部機密 / 實名追溯',
    AppLanguage.english: 'Internal Confidential / Traceable',
    AppLanguage.japanese: '内部機密 / 実名追跡',
  },
  'pickupStorageLocationLabel': {
    AppLanguage.simplifiedChinese: '存放位置',
    AppLanguage.traditionalChinese: '存放位置',
    AppLanguage.english: 'Storage Location',
    AppLanguage.japanese: '保管位置',
  },
  'pickupStorageLocationValue': {
    AppLanguage.simplifiedChinese: 'A区 · {doorNo}号柜门 · 第二层',
    AppLanguage.traditionalChinese: 'A區 · {doorNo} 號櫃門 · 第二層',
    AppLanguage.english: 'Zone A · Door {doorNo} · Level 2',
    AppLanguage.japanese: 'Aエリア · 扉 {doorNo} · 2段目',
  },
  'pickupRequestNoLabel': {
    AppLanguage.simplifiedChinese: '申请单号',
    AppLanguage.traditionalChinese: '申請單號',
    AppLanguage.english: 'Request No.',
    AppLanguage.japanese: '申請番号',
  },
  'pickupRequestNoValue': {
    AppLanguage.simplifiedChinese: 'SC-PICKUP-20260612-0008',
    AppLanguage.traditionalChinese: 'SC-PICKUP-20260612-0008',
    AppLanguage.english: 'SC-PICKUP-20260612-0008',
    AppLanguage.japanese: 'SC-PICKUP-20260612-0008',
  },
  'pickupAuthorizedAtLabel': {
    AppLanguage.simplifiedChinese: '授权时间',
    AppLanguage.traditionalChinese: '授權時間',
    AppLanguage.english: 'Authorized At',
    AppLanguage.japanese: '認可時刻',
  },
  'pickupAuthorizedAtValue': {
    AppLanguage.simplifiedChinese: '2026年6月12日 13:45:46',
    AppLanguage.traditionalChinese: '2026年6月12日 13:45:46',
    AppLanguage.english: 'Jun 12, 2026 13:45:46',
    AppLanguage.japanese: '2026年6月12日 13:45:46',
  },
  'pickupDoorInfoBack': {
    AppLanguage.simplifiedChinese: '返回验证',
    AppLanguage.traditionalChinese: '返回驗證',
    AppLanguage.english: 'Back to Verification',
    AppLanguage.japanese: '認証へ戻る',
  },
  'pickupDoorInfoOpenDoor': {
    AppLanguage.simplifiedChinese: '确认打开柜门',
    AppLanguage.traditionalChinese: '確認開啟櫃門',
    AppLanguage.english: 'Open Cabinet Door',
    AppLanguage.japanese: '扉を開く',
  },
  'pickupDoorInfoIdentitySummary': {
    AppLanguage.simplifiedChinese: '身份链路完整，四重认证均已通过。本次取件行为将自动写入审计日志。',
    AppLanguage.traditionalChinese: '身份鏈路完整，四重驗證均已通過。本次取件行為將自動寫入審計日誌。',
    AppLanguage.english:
        'Identity chain complete. All four verifications passed. This pickup will be written to the audit log automatically.',
    AppLanguage.japanese:
        '本人確認チェーンは完全です。四重認証はすべて完了しており、本次の受取操作は自動的に監査ログへ記録されます。',
  },
  'pickupEmployeeCodeLabel': {
    AppLanguage.simplifiedChinese: '员工编号',
    AppLanguage.traditionalChinese: '員工編號',
    AppLanguage.english: 'Employee ID',
    AppLanguage.japanese: '社員番号',
  },
  'pickupPhoneLabel': {
    AppLanguage.simplifiedChinese: '手机号码',
    AppLanguage.traditionalChinese: '手機號碼',
    AppLanguage.english: 'Phone Number',
    AppLanguage.japanese: '電話番号',
  },
  'pickupIdCardLabel': {
    AppLanguage.simplifiedChinese: '证件号码',
    AppLanguage.traditionalChinese: '證件號碼',
    AppLanguage.english: 'ID Number',
    AppLanguage.japanese: '身分証番号',
  },
  'pickupOrganizationLabel': {
    AppLanguage.simplifiedChinese: '所属机构',
    AppLanguage.traditionalChinese: '所屬機構',
    AppLanguage.english: 'Organization',
    AppLanguage.japanese: '所属組織',
  },
  'pickupPermissionLevelLabel': {
    AppLanguage.simplifiedChinese: '权限等级',
    AppLanguage.traditionalChinese: '權限等級',
    AppLanguage.english: 'Permission Level',
    AppLanguage.japanese: '権限レベル',
  },
  'pickupFaceLabel': {
    AppLanguage.simplifiedChinese: '人脸识别',
    AppLanguage.traditionalChinese: '人臉識別',
    AppLanguage.english: 'Face Recognition',
    AppLanguage.japanese: '顔認証',
  },
  'pickupFingerprintLabel': {
    AppLanguage.simplifiedChinese: '指纹识别',
    AppLanguage.traditionalChinese: '指紋識別',
    AppLanguage.english: 'Fingerprint Scan',
    AppLanguage.japanese: '指紋認証',
  },
  'pickupNfcLabel': {
    AppLanguage.simplifiedChinese: 'NFC识别',
    AppLanguage.traditionalChinese: 'NFC識別',
    AppLanguage.english: 'NFC Scan',
    AppLanguage.japanese: 'NFC認証',
  },
  'pickupCodeLabel': {
    AppLanguage.simplifiedChinese: '取件码',
    AppLanguage.traditionalChinese: '取件碼',
    AppLanguage.english: 'Pickup Code',
    AppLanguage.japanese: '受取コード',
  },
  'pickupSuccessTitle': {
    AppLanguage.simplifiedChinese: '取件成功',
    AppLanguage.traditionalChinese: '取件成功',
    AppLanguage.english: 'Pickup Successful',
    AppLanguage.japanese: '受取完了',
  },
  'pickupCloseDoorHint': {
    AppLanguage.simplifiedChinese: '请及时关闭柜门，系统将自动上锁',
    AppLanguage.traditionalChinese: '請及時關閉櫃門，系統將自動上鎖',
    AppLanguage.english:
        'Please close the cabinet door promptly. The system will lock automatically.',
    AppLanguage.japanese: '扉を速やかに閉めてください。システムが自動で施錠します。',
  },
  'pickupReturnHome': {
    AppLanguage.simplifiedChinese: '返回首页',
    AppLanguage.traditionalChinese: '返回首頁',
    AppLanguage.english: 'Back Home',
    AppLanguage.japanese: 'ホームへ戻る',
  },
  'pickupLockDoor': {
    AppLanguage.simplifiedChinese: '锁定柜门',
    AppLanguage.traditionalChinese: '鎖定櫃門',
    AppLanguage.english: 'Lock Door',
    AppLanguage.japanese: '扉を施錠',
  },
  'pickupAutoReturnHome': {
    AppLanguage.simplifiedChinese: '{seconds}s 后自动返回首页',
    AppLanguage.traditionalChinese: '{seconds}s 後自動返回首頁',
    AppLanguage.english: 'Returning home in {seconds}s',
    AppLanguage.japanese: '{seconds} 秒後にホームへ戻ります',
  },
};
